"""배포 모델 보호 도구. 세부 방식과 키 관리는 개발 PC의 비공개 문서를 따른다.
키 파일과 생성물은 공개 저장소에 넣지 않는다.

  python tools/model_crypt.py genkey --tag models-v1
  python tools/model_crypt.py emit --tag models-v1
  python tools/model_crypt.py encrypt --tag models-v1 IN.gguf OUT.gguf.enc
  python tools/model_crypt.py check --tag models-v1 OUT.gguf.enc
"""
import argparse
import json
import os
import secrets

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

KEY_DIR = "E:/Git_Project/stigma-train/keys"
INC_PATH = "E:/Git_Project/stigma-train/toolchain/llama.cpp-stigma/ggml/src/stigma-key.inc"
GAME_KEY_PATH = "E:/Git_Project/T_RPG/개발/gm_key.py"
CHUNK = 64 << 20


def key_path(tag):
    return os.path.join(KEY_DIR, f"{tag}.json")


def load(tag):
    with open(key_path(tag), encoding="utf-8") as f:
        k = json.load(f)
    return bytes.fromhex(k["bin_half"]), bytes.fromhex(k["game_half"])


def full_key(tag):
    a, b = load(tag)
    return bytes(x ^ y for x, y in zip(a, b))


def cipher(key, size):
    nonce = size.to_bytes(8, "big") + (0).to_bytes(8, "big")
    return Cipher(algorithms.AES(key), modes.CTR(nonce)).encryptor()


def c_array(b):
    return ", ".join(f"0x{x:02x}" for x in b)


def emit(tag):
    a, b = load(tag)
    m1 = secrets.token_bytes(32)
    m2 = bytearray(32)
    for i in range(32):
        m2[31 - i] = a[i] ^ m1[i] ^ ((i * 37 + 11) & 0xFF)
    with open(INC_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(f"// generated by stigma-gm/tools/model_crypt.py ({tag}) - never commit\n")
        f.write("static void stigma_bin_half(uint8_t out[32]) {\n")
        f.write(f"    static const volatile uint8_t m1[32] = {{ {c_array(m1)} }};\n")
        f.write(f"    static const volatile uint8_t m2[32] = {{ {c_array(m2)} }};\n")
        f.write("    for (int i = 0; i < 32; i++) {\n")
        f.write("        out[i] = (uint8_t) (m1[i] ^ m2[31 - i] ^ (uint8_t) (i*37 + 11));\n")
        f.write("    }\n}\n")

    g1 = secrets.token_bytes(32)
    g2 = bytearray(32)
    for i in range(32):
        g2[(i * 13) % 32] = b[i] ^ g1[i] ^ ((i * 71 + 5) & 0xFF)
    with open(GAME_KEY_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(f'"""생성 파일 (stigma-gm/tools/model_crypt.py, {tag}). 공개 저장소에 올리지 않는다 (.gitignore)."""\n')
        f.write(f"TAG = {tag!r}\n")
        f.write(f"_A = bytes([{c_array(g1)}])\n")
        f.write(f"_B = bytes([{c_array(g2)}])\n\n\n")
        f.write("def half_hex():\n")
        f.write("    return bytes(_A[i] ^ _B[(i * 13) % 32] ^ ((i * 71 + 5) & 0xFF) for i in range(32)).hex()\n")
        # 워터마크 누출 검사 해시 (engine/guard.py가 읽는다). 공개 단어 목록으로 되돌릴 수 있어 공개 코드에 두지 않는다
        wm_path = os.path.join(KEY_DIR, "wm_guard.json")
        if os.path.exists(wm_path):
            with open(wm_path, encoding="utf-8") as w:
                wm = json.load(w)
            f.write("\n\n# 워터마크 누출 검사용 해시 (engine/guard.py). 공개 단어 목록으로 되돌릴 수 있어 공개 코드에 두지 않는다\n")
            f.write(f"WM_SIG = {set(wm['sig'])!r}\n")
            f.write(f"WM_FRAME = {set(wm['frame'])!r}\n")
    print("wrote", INC_PATH)
    print("wrote", GAME_KEY_PATH)


def genkey(tag):
    os.makedirs(KEY_DIR, exist_ok=True)
    if os.path.exists(key_path(tag)):
        raise SystemExit(f"{key_path(tag)} 이미 있음. 덮어쓰면 이 태그로 배포한 모델을 못 푼다.")
    with open(key_path(tag), "w", encoding="utf-8") as f:
        json.dump({"tag": tag, "bin_half": secrets.token_hex(32), "game_half": secrets.token_hex(32)}, f, indent=2)
    print("wrote", key_path(tag), "(백업해 둘 것)")
    emit(tag)


def encrypt(tag, src, dst):
    size = os.path.getsize(src)
    enc = cipher(full_key(tag), size)
    done = 0
    with open(src, "rb") as fi, open(dst + ".tmp", "wb") as fo:
        while True:
            buf = fi.read(CHUNK)
            if not buf:
                break
            fo.write(enc.update(buf))
            done += len(buf)
            print(f"\r{done / size * 100:5.1f}%", end="", flush=True)
        fo.write(enc.finalize())
    os.replace(dst + ".tmp", dst)
    print(f"\n{src} -> {dst} ({size:,} bytes)")


def check(tag, path):
    size = os.path.getsize(path)
    with open(path, "rb") as f:
        head = f.read(16)
    plain = cipher(full_key(tag), size).update(head)
    ok = plain[:4] == b"GGUF" and head[:4] != b"GGUF"
    print(path, "OK (암호화됨, 키로 풀림)" if ok else f"FAIL head={head[:4]!r} plain={plain[:4]!r}")
    return ok


def main():
    p = argparse.ArgumentParser()
    p.add_argument("cmd", choices=["genkey", "emit", "encrypt", "check"])
    p.add_argument("--tag", default="models-v1")
    p.add_argument("paths", nargs="*")
    a = p.parse_args()
    if a.cmd == "genkey":
        genkey(a.tag)
    elif a.cmd == "emit":
        emit(a.tag)
    elif a.cmd == "encrypt":
        encrypt(a.tag, *a.paths)
    else:
        raise SystemExit(0 if all(check(a.tag, x) for x in a.paths) else 1)


if __name__ == "__main__":
    main()
