# equipment_en.py — 장비 이름·설명 영어 번역 표
# db_init.py의 equipment_data와 item_id로 1:1 대응한다. 값: (name_en, description_en)

EQUIPMENT_EN = {
    # [기본 지급]
    "WEAPON_NONE": ("Bare Hands", "[Basic] The organic striking tools you were born with."),

    # ===== [4등급: 급조 (Scrap)] =====
    # --- 주무기 (main_weapon) ---
    "WEAPON_SCRAP_01": ("Rusted Scrap Blade", "[T=4 Makeshift] A blade roughly ground from a wrecked car's suspension spring. It rings with a grating whine."),
    "WEAPON_SCRAP_02": ("Discarded Rivet Gun", "[T=4 Makeshift] A gas-powered rivet gun scavenged from a construction site. Fires iron spikes with a harsh grinding noise."),
    "WEAPON_SCRAP_03": ("Discharge Spanner", "[T=4 Makeshift] An oversized off-spec spanner wrapped with an old battery. Sparks fly on impact."),
    "WEAPON_SCRAP_04": ("Contaminated Flame Pipe", "[T=4 Makeshift] A high-risk flamethrower made by hooking gasoline straight into a gas pipe with no filter."),
    "WEAPON_SCRAP_05": ("Rebar Concrete Bludgeon", "[T=4 Makeshift] A heavy length of rebar torn from collapsed rubble, a chunk of concrete still fixed to its end."),
    "WEAPON_SCRAP_06": ("Sharp Glass Shard Spear", "[T=4 Makeshift] A spear made by taping shattered tempered glass from a corporate tower to the end of a long pipe."),
    "WEAPON_SCRAP_07": ("Worn Industrial Sawblade", "[T=4 Makeshift] A crude throwing blade: a toothless circular saw with leather wrapped on as a grip."),
    "WEAPON_SCRAP_08": ("Exposed-Wire Choke Stick", "[T=4 Makeshift] High-voltage cable coiled around a silicone rod, delivering blunt force and electric shock at once."),
    "WEAPON_SCRAP_09": ("Makeshift Powder Pipe Burst", "[T=4 Makeshift] A crude gun that detonates gunpowder inside an iron pipe to spray shot. Feels single-use."),
    "WEAPON_SCRAP_10": ("Rusted Junkyard Hatchet", "[T=4 Makeshift] A dull-edged scrap hatchet that was lying around a waste processing yard."),
    # --- 사이버덱 (cyberdeck) ---
    "DECK_SCRAP_01": ("Half-Burnt Motherboard", "[T=4 Makeshift] A crude compute board built from a few chipsets salvaged out of a burnt corporate terminal."),
    "DECK_SCRAP_02": ("Waterlogged Terminal", "[T=4 Makeshift] Fished out of a sewer node and merely wiped dry. The screen flickers every few seconds."),
    "DECK_SCRAP_03": ("Old Signal Receiver", "[T=4 Makeshift] A bootleg rig: a router from a dead cell tower strapped to the wrist with rubber bands."),
    "DECK_SCRAP_04": ("Cracking Transistor", "[T=4 Makeshift] A module that reverse-wires analog radio components to forcibly tangle firewall packets."),
    "DECK_SCRAP_05": ("Wrecked-Car Navigation Deck", "[T=4 Makeshift] A cyberdeck made by force-encoding an abandoned motorbike's GPS board with a Net Force OS."),
    "DECK_SCRAP_06": ("Rusted Compute Microchip", "[T=4 Makeshift] A core panel pulled from the brain of a scrap-cleaning drone, its circuits half burnt out."),
    "DECK_SCRAP_07": ("Makeshift Copper Wire Panel", "[T=4 Makeshift] A device of copper wire wound into coils to snag faint electromagnetic signals."),
    "DECK_SCRAP_08": ("Modded Barcode Scanner Gadget", "[T=4 Makeshift] An old-world store barcode reader modified to read basic firewall code."),
    "DECK_SCRAP_09": ("Faulty Radio Module", "[T=4 Makeshift] An old analog transceiver so noisy that even the Master AI gives up analyzing it."),
    "DECK_SCRAP_10": ("Scavenger Custom Log Board", "[T=4 Makeshift] A device that parses log text using several discarded calculator displays wired in series."),
    # --- 의체부품 (cybernetic_parts) ---
    "CYBER_SCRAP_01": ("Reclaimed Hydraulic Cylinder", "[T=4 Makeshift] A cylinder pulled from a freight elevator. Lets out a harsh metallic shriek when it moves."),
    "CYBER_SCRAP_02": ("Exposed Copper Neural Wiring", "[T=4 Makeshift] Stripped wires soldered straight onto the spine, causing constant faint tremors."),
    "CYBER_SCRAP_03": ("Waste-Crusher Prosthetic Hand", "[T=4 Makeshift] A crude cybernetic hand: an industrial crusher claw miniaturized and welded to the wrist."),
    "CYBER_SCRAP_04": ("Makeshift Motor Heart", "[T=4 Makeshift] Bioware that syncs a motorbike starter motor's drive shaft with an artificial heartbeat."),
    "CYBER_SCRAP_05": ("Rusted Servo Ankle", "[T=4 Makeshift] A vacuum cleaner motor jammed into the ankle joint. Very noisy with every tick."),
    "CYBER_SCRAP_06": ("Junk-Wire Artificial Muscle", "[T=4 Makeshift] Crude body-augmentation made by twisting discarded rubber tubes and copper wire bundles."),
    "CYBER_SCRAP_07": ("Drone-Joint Grafted Arm", "[T=4 Makeshift] A cybernetic arm: a wrecked recon drone's wing-axle joint forcibly screwed into the shoulder blade."),
    "CYBER_SCRAP_08": ("Analog Pressure-Sensing Eye", "[T=4 Makeshift] The aperture of a broken-lens analog camera set into an empty eye socket."),
    "CYBER_SCRAP_09": ("Scrap-Plate Rib Brace", "[T=4 Makeshift] Scrap panels riveted directly onto both sides of the chest to prevent thoracic damage."),
    "CYBER_SCRAP_10": ("Old Memory Injector Filter", "[T=4 Makeshift] A water purifier filter wired in series with a memory chip and set into the back of the neck to prevent brain damage."),
    # --- 등 장비 (back_gear) ---
    "BACK_SCRAP_01": ("Scrap Handcart Frame", "[T=4 Makeshift] A crude pack frame: a broken handcart's wheels and skeleton strapped to the back with leather."),
    "BACK_SCRAP_02": ("Rusted Steel Lockbox", "[T=4 Makeshift] A metal switchboard box, door and all, slung from a leather belt as a bag."),
    "BACK_SCRAP_03": ("Wire-Bound Sling Pack", "[T=4 Makeshift] A sling bag patched together from torn tarp scraps stitched with copper wire."),
    "BACK_SCRAP_04": ("Drone-Wing Makeshift Harness", "[T=4 Makeshift] A drone propeller guard fixed to the chest to balance the weight on the back."),
    "BACK_SCRAP_05": ("Half-Burnt Solar Panel", "[T=4 Makeshift] An old backpack charging panel with a shattered surface that barely produces a trickle of current."),
    "BACK_SCRAP_06": ("Scrap-Tire Rubber Backpack", "[T=4 Makeshift] A bag cut from a motorcycle tire, its opening sealed with copper wire instead of a zipper."),
    "BACK_SCRAP_07": ("Industrial Heat-Vent Fan", "[T=4 Makeshift] A cooling rig of several PC fans soldered to a back plate to keep the chassis from overheating."),
    "BACK_SCRAP_08": ("Radio Antenna Backpack", "[T=4 Makeshift] A traffic-light antenna pole lashed to a backpack frame to boost signal sensitivity."),
    "BACK_SCRAP_09": ("Contaminated Mattress-Hide Sack", "[T=4 Makeshift] A huge sack torn from discarded mattress covers, stuffed with resources without care."),
    "BACK_SCRAP_10": ("Makeshift Battery Rig", "[T=4 Makeshift] A frame that straps a series of assorted dead batteries to the back."),
    # --- 안면 (face) ---
    "FACE_SCRAP_01": ("Scrap Shard Mask", "[T=4 Makeshift] A steel plate with two rough eyeholes, strapped to the face with leather."),
    "FACE_SCRAP_02": ("Cracked Gas Mask Shell", "[T=4 Makeshift] Its filter no longer purifies anything, but it barely stops blows to the face."),
    "FACE_SCRAP_03": ("Old Analog Welding Mask", "[T=4 Makeshift] Plastic welding shade goggles. Narrows your vision but blocks sparks from the front."),
    "FACE_SCRAP_04": ("Tape-Wrapped Sunglasses", "[T=4 Makeshift] Glasses with broken arms taped around the head. Little effect beyond style."),
    "FACE_SCRAP_05": ("Shattered Bike Helmet", "[T=4 Makeshift] A cracked motorcycle helmet missing its visor. The worn chin strap dangles loose."),
    "FACE_SCRAP_06": ("Contaminated Filter Mask", "[T=4 Makeshift] A mouth cover of layered rags to filter out dust and scrap powder."),
    "FACE_SCRAP_07": ("Smashed Display Goggles", "[T=4 Makeshift] A blindfold of cracked monitor glass fixed before the eyes to parse tiny text computations."),
    "FACE_SCRAP_08": ("Landline Handset Band", "[T=4 Makeshift] A crude headset: a cord-cut phone receiver banded to the head to protect the ears."),
    "FACE_SCRAP_09": ("Thick Leather Blindfold", "[T=4 Makeshift] A band that physically dims the Master AI's scan lasers to preserve perception."),
    "FACE_SCRAP_10": ("Barbed Wire Face Guard", "[T=4 Makeshift] A grotesque, menacing mask of barbed wire coiled across the front of the face."),
    # --- 상의외장 (top) ---
    "TOP_SCRAP_01": ("Irradiated Rag Coat", "[T=4 Makeshift] A worn long coat of unknown origin, caked in layer upon layer of contaminated wasteland dust."),
    "TOP_SCRAP_02": ("Thick Tire Armor Pads", "[T=4 Makeshift] Armor cut from a large truck tire and riveted onto the shoulders and chest."),
    "TOP_SCRAP_03": ("Leather Sack Shoulder Guard", "[T=4 Makeshift] An overgarment of layered leather scraps from a broken sofa to protect the shoulder joints."),
    "TOP_SCRAP_04": ("Discarded Corporate Ballistic Scraps", "[T=4 Makeshift] A fiber chest guard dumped by corporate security, torn and holed all over."),
    "TOP_SCRAP_05": ("Plastic Tree-Guard Armor", "[T=4 Makeshift] Plastic street-tree guard panels tied over the chest and belly to spread impacts."),
    "TOP_SCRAP_06": ("Rusted Half-Drum Breastplate", "[T=4 Makeshift] A heavy, clumsy top made from a steel drum cut in half to wrap the body."),
    "TOP_SCRAP_07": ("Wire-Woven Scrap Mail", "[T=4 Makeshift] A fairly tight vest hand-woven from thousands of copper wire rings."),
    "TOP_SCRAP_08": ("Industrial Insulating Rubber Padding", "[T=4 Makeshift] Anti-shock padding lined with insulating rubber mats cut from a substation floor."),
    "TOP_SCRAP_09": ("PC Case Armor", "[T=4 Makeshift] A desktop PC's steel side panel strapped to the chest to stop stabs."),
    "TOP_SCRAP_10": ("Scavenger Studded Vest", "[T=4 Makeshift] A cotton vest densely studded with nails and screws to wound anyone who gets close."),
    # --- 하의외장 (bottom) ---
    "BOTTOM_SCRAP_01": ("Grease-Soaked Work Pants", "[T=4 Makeshift] Jeans stiffened with caked engine oil from rolling through sewer nodes and junkyards."),
    "BOTTOM_SCRAP_02": ("Insulating Tape Overalls", "[T=4 Makeshift] Overalls wrapped head to toe in black electrical tape for waterproofing and anti-discharge."),
    "BOTTOM_SCRAP_03": ("Dead Zone Nomad Rag Pants", "[T=4 Makeshift] Wasteland survival pants made of countless cloth scraps stitched together with wire."),
    "BOTTOM_SCRAP_04": ("Heavily Modded Car-Seat Pants", "[T=4 Makeshift] Sturdy pants patched at the thighs and shins with leather torn from car seats."),
    "BOTTOM_SCRAP_05": ("Industrial Plastic Shin Guards", "[T=4 Makeshift] Crude shin guards: PVC pipe split in half and tied below the knees."),
    "BOTTOM_SCRAP_06": ("Military Tent Cargo Pants", "[T=4 Makeshift] Scavenger pants with a huge number of pockets, made from discarded waterproof tent canvas."),
    "BOTTOM_SCRAP_07": ("Plate-Overlay Tactical Skirt", "[T=4 Makeshift] Light tin plates hung from the waist to reduce the chance of lower-body hits."),
    "BOTTOM_SCRAP_08": ("Fire-Hose Woven Pants", "[T=4 Makeshift] Special pants spliced from tough fire hose, highly resistant to blades."),
    "BOTTOM_SCRAP_09": ("Contaminated Conveyor-Belt Guard", "[T=4 Makeshift] Armored pants of rubber conveyor belt from ruined factories, wrapping the pelvis and hips."),
    "BOTTOM_SCRAP_10": ("Squatter Low-Rise Denim", "[T=4 Makeshift] Worn jeans with blown-out knees, scrap shards loosely chained over the holes."),
    # --- 신발외장 (footwear) ---
    "SHOES_SCRAP_01": ("Makeshift Tire Boots", "[T=4 Makeshift] Boots soled with tread cut from scrap tires and fastened with wire."),
    "SHOES_SCRAP_02": ("Wire-Bound Safety Shoes", "[T=4 Makeshift] Worn construction safety shoes with exposed steel toes, wound with hair-thin wire."),
    "SHOES_SCRAP_03": ("Limiter-Off Servo Boots", "[T=4 Makeshift] Broken cybernetic shoes with their servo motors forcibly wired in series. They creak with every step."),
    "SHOES_SCRAP_04": ("Thick Industrial Rubber Boots", "[T=4 Makeshift] Boots from a chemical plant. Slightly reduces radiation contamination drain."),
    "SHOES_SCRAP_05": ("Spring-Loaded Scrap Shoes", "[T=4 Makeshift] Car valve springs welded to the soles, nudging your turn speed (INIT)."),
    "SHOES_SCRAP_06": ("Kevlar-Patched Sneakers", "[T=4 Makeshift] Stray sneakers with scraps of ballistic cloth glued all over them."),
    "SHOES_SCRAP_07": ("Tin-Reinforced Desert Boots", "[T=4 Makeshift] Military desert boots lined with tin plates to stop nails from piercing the soles."),
    "SHOES_SCRAP_08": ("Scrap-Studded Leather Boots", "[T=4 Makeshift] Wasteland boots: full-leather boots with dozens of screws driven into the soles for grip."),
    "SHOES_SCRAP_09": ("Plastic-Wrapped Flats", "[T=4 Makeshift] Shoes burst apart, held together by leather scraps and industrial stretch film."),
    "SHOES_SCRAP_10": ("Modded Drone-Skid Shoes", "[T=4 Makeshift] A small drone's landing-skid frame strapped under the feet like sandals."),
    # --- 목걸이 (necklace) ---
    "NECK_SCRAP_01": ("Copper Wire Necklace", "[T=4 Makeshift] Thick copper cable cut from a substation and bent round to fit the neck."),
    "NECK_SCRAP_02": ("Burnt RAM Pendant", "[T=4 Makeshift] A trinket: a megacorp server RAM stick, its circuits fried by overheating, hung on a cord."),
    "NECK_SCRAP_03": ("Drone Camera Lens Choker", "[T=4 Makeshift] A choker made from a downed recon drone's optical lens guide, strapped tight with leather."),
    "NECK_SCRAP_04": ("Wheezing Artificial Voicebox Band", "[T=4 Makeshift] A neckband of old voice-changer parts that turns your voice into mechanical log tones."),
    "NECK_SCRAP_05": ("Corporate Employee ID Tag", "[T=4 Makeshift] A pendant: the plastic ID card of a long-dead corporate subcontractor on a chain."),
    "NECK_SCRAP_06": ("Series Fuse Necklace", "[T=4 Makeshift] A bizarre necklace strung from five blown industrial high-voltage overload fuses."),
    "NECK_SCRAP_07": ("Mech-Beast Coolant Necklace", "[T=4 Makeshift] A necklace braided from clear coolant tubes pulled from a Bio Hound's nape."),
    "NECK_SCRAP_08": ("Cyberdeck Ground-Plug Choker", "[T=4 Makeshift] A broken plastic connector once used to ground a cyberdeck to the body, worn as a necklace."),
    "NECK_SCRAP_09": ("Shell Casing Necklace", "[T=4 Makeshift] Ten spent Resistance rifle casings strung on copper wire, hanging across the chest."),
    "NECK_SCRAP_10": ("Tin Can Pull-Tab Necklace", "[T=4 Makeshift] Dozens of old-world can pull-tabs woven together. It jingles with every move."),
    # --- 반지 (ring) ---
    "RING_SCRAP_01": ("Rusted Nut Ring", "[T=4 Makeshift] A hex nut from a factory floor, roughly ground down to finger size."),
    "RING_SCRAP_02": ("Mech-Beast Fang Ring", "[T=4 Makeshift] A broken titanium-alloy fang of a canine mech-beast, wrapped in copper wire."),
    "RING_SCRAP_03": ("Soldered Washer Ring", "[T=4 Makeshift] Several copper wiring washers stacked and soldered to fit the finger."),
    "RING_SCRAP_04": ("Fiber-Optic Knot Ring", "[T=4 Makeshift] A knot ring neatly twisted from a snapped fiber-optic cable glowing fluorescent yellow."),
    "RING_SCRAP_05": ("Cyberdeck Dial Knob Ring", "[T=4 Makeshift] The aluminum volume dial pried off a broken cyberdeck and fitted onto a finger."),
    "RING_SCRAP_06": ("Small Spring Ring", "[T=4 Makeshift] A crude gadget ring: a tiny return spring from precision machinery coiled around the finger."),
    "RING_SCRAP_07": ("LED Glow Ring", "[T=4 Makeshift] A dying red LED wired to a mercury cell, glowing on your finger at all times."),
    "RING_SCRAP_08": ("Corporate Security Chip Signet", "[T=4 Makeshift] A signet ring: an expired corporate door-lock smart chip mounted on a scrap plate."),
    "RING_SCRAP_09": ("Stripped Triple-Wire Ring", "[T=4 Makeshift] A light ring of red, blue, and yellow wires stripped and twisted like shielded cable."),
    "RING_SCRAP_10": ("Old Proxy Key Card Fragment", "[T=4 Makeshift] A ring set with the chip of a disposable security card once used to launder virtual safehouse nodes."),
    # --- 특화부품 (custom_part) ---
    "PART_SCRAP_01": ("Crude Current Bypass", "[T=4 Makeshift] [Combat] Unique skill [Overclock] duration +1 turn / [Penalty] Lose a fixed 100 HP every turn while active."),
    "PART_SCRAP_02": ("Rusted Solder Heatsink", "[T=4 Makeshift] [Net] Power of basic RAM-cost cyberdeck skills +2% / [Penalty] Firewall index (Alert) +3 extra on successful hacks."),
    "PART_SCRAP_03": ("Old Discharge Capacitor", "[T=4 Makeshift] [Combat] Crit chance +3% permanently / [Penalty] Initiative index (INIT) always -5 at the start of combat."),
    "PART_SCRAP_04": ("Recycled Resistor Coil", "[T=4 Makeshift] [Net] Base RAM recovery delay -1 turn during [Grid Intrude] / [Penalty] Max RAM forcibly locked at -1 for that combat."),
    "PART_SCRAP_05": ("Radio Antenna Receiver Tip", "[T=4 Makeshift] [Utility] +0.5% to the 1% ghost data box detection rate when searching the field / [Penalty] Mech-beast ambush rate x1.5."),
    "PART_SCRAP_06": ("Manual Lubricant Pump", "[T=4 Makeshift] [Combat] [Bio Reap] success chance +2% permanently / [Penalty] Hunger/thirst drain always +1 faster at end of each turn."),
    "PART_SCRAP_07": ("Contaminated Proxy Filter Chip", "[T=4 Makeshift] [Net] [Protocol Glitch] log forgery success +2% / [Penalty] Brain damage from a failed forgery doubled."),
    "PART_SCRAP_08": ("Clock-Over Spark Element", "[T=4 Makeshift] [Combat] Main weapon basic attack damage multiplier +5% / [Penalty] 5% chance the weapon shuts down for 1 turn when skills run at full load."),
    "PART_SCRAP_09": ("Soldered Memory Dump", "[T=4 Makeshift] [Net] Resistance to hacking debuff stacking +5% permanently / [Penalty] Flee success chance -10%."),
    "PART_SCRAP_10": ("Drone Gyro Sensor Fitting", "[T=4 Makeshift] [Combat] Initiative index (INIT) +6 permanently / [Penalty] Base physical defense fixed at -5."),

    # ===== [3등급: 규격 (Standard)] =====
    # --- 주무기 (main_weapon) ---
    "WEAPON_STD_01": ("Scrap Coalition Service Rifle", "[T=3 Standard] The Resistance's dependable standard-issue rifle, firing 7.62mm rounds reliably."),
    "WEAPON_STD_02": ("Ultrasonic Scrap Dagger", "[T=3 Standard] An assassin's blade whose built-in pack vibrates at high speed, shredding machine plating in seconds."),
    "WEAPON_STD_03": ("Rail Magnetic Pistol", "[T=3 Standard] A standard pistol that pushes slugs through subsonic speed along neatly aligned electromagnetic rails."),
    "WEAPON_STD_04": ("Junkyard Heavy Sledge", "[T=3 Standard] A heavy maul with an industrial hydraulic accelerator nozzle fused to its head for maximum steel-crushing force."),
    "WEAPON_STD_05": ("High-Voltage Spark Saber", "[T=3 Standard] A sword with a plasma arc constantly circling its blade, discharging current on every hit."),
    "WEAPON_STD_06": ("Modified Compact Shotgun", "[T=3 Standard] A scavenger shotgun with devastating burst damage in close-quarters clashes."),
    "WEAPON_STD_07": ("Frequency-Jamming Revolver", "[T=3 Standard] A revolver that fires special rounds with digital shredding code encoded into the cylinder."),
    "WEAPON_STD_08": ("Resistance Precision Sniper Rifle", "[T=3 Standard] A long-barreled manual bolt-action rifle that reliably delivers long-range sniper logs."),
    "WEAPON_STD_09": ("Underbarrel Grenade Launcher", "[T=3 Standard] A standard launcher at the peak of its power bracket, spraying a wide-area shrapnel destruction script."),
    "WEAPON_STD_10": ("Servo-Driven Combat Knife", "[T=3 Standard] A dagger with a small servo motor in the grip that boosts thrust speed and penetration."),
    # --- 사이버덱 (cyberdeck) ---
    "DECK_STD_01": ("Wasteland Squatter Custom Deck", "[T=3 Standard] The hacker's standard rig: a Linux shell for firewall-bypass nodes soldered onto standard hardware."),
    "DECK_STD_02": ("Recycled Cracker v2", "[T=3 Standard] A Net Force cyberdeck rebuilt from a discarded corporate comms terminal with darknet-only protocols."),
    "DECK_STD_03": ("Frequency Jamming Board", "[T=3 Standard] A device that disrupts sync by periodically broadcasting white noise into nearby Master AI signal nets."),
    "DECK_STD_04": ("Linux Architecture Deck", "[T=3 Standard] A compute unit running a transplanted old-world open-source OS, with an extremely low packet-tampering error rate."),
    "DECK_STD_05": ("Matrix Signal Bypasser", "[T=3 Standard] A deck that routes around signal-tracing circuits the analog way when laundering virtual safehouse nodes."),
    "DECK_STD_06": ("Junkyard Motherboard Deck", "[T=3 Standard] A gadget with a heavily modded old northbridge chipset for more efficient multi-packet projection."),
    "DECK_STD_07": ("Digital Smuggler Link", "[T=3 Standard] A deck that compresses data packets when a guerrilla infiltrator forcibly extracts (smuggles) resources."),
    "DECK_STD_08": ("Firewall-Aware Sensor Board", "[T=3 Standard] A compute unit that back-traces every point of change in the firewall trace index (Alert) upon entering the city."),
    "DECK_STD_09": ("Open Net Relay Server Chip", "[T=3 Standard] A device that keeps a stable breach in virtual reality protocols even in radio dead spots."),
    "DECK_STD_10": ("Resistance Tactical Log Processor", "[T=3 Standard] A cyberdeck that optimizes analysis logs on enemy mech-beasts at the end of every combat turn."),
    # --- 의체부품 (cybernetic_parts) ---
    "CYBER_STD_01": ("Reinforced Titanium Joint", "[T=3 Standard] Standardized titanium-alloy parts that raise the physical load limits of knees and elbows."),
    "CYBER_STD_02": ("Junkyard Servo Motor", "[T=3 Standard] A high-torque motor precision-rebuilt in a Scrap Coalition workshop. Locks in your grip strength."),
    "CYBER_STD_03": ("Standard Synthetic Muscle Bundle", "[T=3 Standard] Artificial polymer fibers that react to bio-current, layered on the thighs to raise mobility."),
    "CYBER_STD_04": ("Analog Hydraulic Spine Bar", "[T=3 Standard] An exoskeletal lattice frame screwed firmly to the spinal column to spread inventory weight."),
    "CYBER_STD_05": ("Bio-Link Feed Connector", "[T=3 Standard] A nape implant that stabilizes neural signal transfer when unique skill points (SP) are injected."),
    "CYBER_STD_06": ("Reinforced Brass Heart Valve", "[T=3 Standard] Manually regulates blood flow via motor voltage to support your base Vitality (HP)."),
    "CYBER_STD_07": ("Digital Optic Sensor Lens", "[T=3 Standard] A standard aperture lens for cybernetic eyes. Scans enemy effective defense second by second."),
    "CYBER_STD_08": ("Shock-Absorbing Rib Plating", "[T=3 Standard] Light alloy plates riveted in a grid across the chest to raise base physical DEF."),
    "CYBER_STD_09": ("Sheathed Neural Insulation Cable", "[T=3 Standard] Wiring that gently deflects the shock recoil of virtual firewalls during direct net access."),
    "CYBER_STD_10": ("Servo-Driven Knee Lattice", "[T=3 Standard] Motor bearings apply counter-torque to protect the joint from falls and sharp turns."),
    # --- 등 장비 (back_gear) ---
    "BACK_STD_01": ("High-Capacity Scrap Backpack", "[T=3 Standard] A bag of waterproof tent canvas on a steel frame that raises carry weight by +10kg."),
    "BACK_STD_02": ("Reinforced Brass Radiator", "[T=3 Standard] A device that vents the heat of running cybernetics outward through copper pipes and cooling fans."),
    "BACK_STD_03": ("Scrap Coalition Ammo Belt Rig", "[T=3 Standard] A tactical harness designed for fast rifle mag and grenade swaps during frontal assaults."),
    "BACK_STD_04": ("Compact Gasoline Generator Pack", "[T=3 Standard] A small backpack generator that constantly supplies current for base barriers and battery charging."),
    "BACK_STD_05": ("Wireless Jeep Antenna Mast", "[T=3 Standard] Improves the detection rate of hidden resource boxes in the field when running Signal Trace."),
    "BACK_STD_06": ("Kevlar-Reinforced Hard-Shell Bag", "[T=3 Standard] A light ballistic hard backpack that fully absorbs surprise shrapnel hits from behind."),
    "BACK_STD_07": ("Multi-Battery Slot Bank", "[T=3 Standard] A backpack wiring several dying cells in parallel to conserve the cyberdeck's available power."),
    "BACK_STD_08": ("Leather Drone Holster", "[T=3 Standard] A rig that safely folds an automation engineer's two autonomous swarm drones onto the back."),
    "BACK_STD_09": ("Discharge Ground Anchor Rail", "[T=3 Standard] A ground line that converts the brain-damage recoil of digital counter-hacks into a shockwave and sinks it into the earth."),
    "BACK_STD_10": ("Lead-Lined Rad-Shield Pack", "[T=3 Standard] Keeps collected resources from contamination damage when crossing irradiated basins."),
    # --- 안면 (face) ---
    "FACE_STD_01": ("Junkyard Dust Goggles", "[T=3 Standard] Goggles that fully block the Dead Zone's wasteland sandstorms and keep basic visibility."),
    "FACE_STD_02": ("Scrap Coalition Tactical Mask", "[T=3 Standard] A gas mask with standardized, easily swapped filters. Guards against barbed-wire slashes."),
    "FACE_STD_03": ("Night Thermal Scanner HUD", "[T=3 Standard] Glasses that parse mech-beast heat signatures inside dark ruined factories and node bases."),
    "FACE_STD_04": ("Variable-Aperture Monocle", "[T=3 Standard] A camera-shutter gimmick set before the eye to boost your crit chance weighting."),
    "FACE_STD_05": ("Industrial Heat-Resistant Face Shield", "[T=3 Standard] A protective mask that stops the searing sparks and flying debris of Mechanical Tech welding."),
    "FACE_STD_06": ("Old Military Ballistic Visor", "[T=3 Standard] A ballistic-coated faceplate that reduces the damage multiplier of frontal sniper rounds."),
    "FACE_STD_07": ("Resistance Camo Face-Paint Mask", "[T=3 Standard] A text-hint cosmetic that slightly lowers ambush rates during field exploration turns."),
    "FACE_STD_08": ("Voice-Forging Packet Mouthpiece", "[T=3 Standard] Launders your vocal signals so the Master AI's surveillance radar cannot recognize them."),
    "FACE_STD_09": ("Fiber-Optic Overlay Shade", "[T=3 Standard] Filters the intense laser light of virtual reality to prevent Intellect (INT) perception paralysis."),
    "FACE_STD_10": ("Recycled Dental Security Mask", "[T=3 Standard] Layered thin metal mesh guards the jaw and mouth against dismemberment logs."),
    # --- 상의외장 (top) ---
    "TOP_STD_01": ("Scrap Coalition Leather Duster", "[T=3 Standard] A coat of thick beast hide with waterproof coating that reduces radiation contamination ticks."),
    "TOP_STD_02": ("Standard Kevlar Tactical Vest", "[T=3 Standard] A ballistic fiber vest that reliably reduces shrapnel damage in analog combat."),
    "TOP_STD_03": ("Scrap-Riveted Breastplate", "[T=3 Standard] Steel plates densely riveted onto a standard leather vest to raise base physical DEF."),
    "TOP_STD_04": ("Resistance Camo Field Jacket", "[T=3 Standard] A junk coat that blends into the colors of the Dead Zone wasteland covering 95% of the world. Good against ambushes."),
    "TOP_STD_05": ("Heat-Resistant Insulated Work Suit", "[T=3 Standard] A suit that blocks 90% of damage from Mechanical Tech workshop heat vents and electrical sparks."),
    "TOP_STD_06": ("Light Duralumin Plate Vest", "[T=3 Standard] A light yet sturdy hybrid top made from aircraft fuselage scraps shaped to guard the chest."),
    "TOP_STD_07": ("Cybernetic Cable-Guard Leather Coat", "[T=3 Standard] Covers exposed cybernetic drive cylinders and copper wiring to prevent ambush severing logs."),
    "TOP_STD_08": ("Lead-Reinforced Rad Shirt", "[T=3 Standard] A heavy vest lined with densely woven lead washers, highly resistant to physical contamination."),
    "TOP_STD_09": ("Cyberdeck-Mount Tactical Padding", "[T=3 Standard] A Net Force guerrilla top with a built-in hard case for a cyberdeck slot on the chest."),
    "TOP_STD_10": ("Scrap Nomad Heavy Coat", "[T=3 Standard] Hardcore survival armor: a leather coat layered with scrap tires and tin plates."),
    # --- 하의외장 (bottom) ---
    "BOTTOM_STD_01": ("Old Insulated Tactical Pants", "[T=3 Standard] Military waterproof pants reinforced with insulated wiring at every seam to block system shock."),
    "BOTTOM_STD_02": ("Reinforced Knee-Pad Overalls", "[T=3 Standard] Thick leather overalls with riveted duralumin knee guards to protect the joints."),
    "BOTTOM_STD_03": ("Dead Zone Hunter Duster Pants", "[T=3 Standard] Pants that won't tear on the wasteland's thorny tangles of sharp scrap shards."),
    "BOTTOM_STD_04": ("Car-Seat Leather Heavy Pants", "[T=3 Standard] Tough armor made from a large sedan's genuine leather seat torn off whole and patched onto the front."),
    "BOTTOM_STD_05": ("PVC Pipe Shin-Guard Pants", "[T=3 Standard] Standard PVC guards on the shins block canine beasts from mauling your lower body."),
    "BOTTOM_STD_06": ("Scrap Coalition Utility Pants", "[T=3 Standard] Tactical pants that hold 20+ tools and fuses for dismantling scrap parts, sorted by pocket."),
    "BOTTOM_STD_07": ("Tin-Plate Over-Pants", "[T=3 Standard] Tin-plate layers strapped over old rag pants with leather to guard the legs against severing."),
    "BOTTOM_STD_08": ("Fire-Hose Woven Tactical Overalls", "[T=3 Standard] High-pressure waterproof fabric structured into overalls. Wears down extremely slowly."),
    "BOTTOM_STD_09": ("Conveyor-Belt Rubber Thigh Pads", "[T=3 Standard] Pants with thick factory conveyor-belt rubber guarding the exposed power lines on both thighs."),
    "BOTTOM_STD_10": ("Resistance Standard Hybrid Jeans", "[T=3 Standard] Scavenger-leader pants: titanium mesh below the knee, Kevlar denim above."),
    # --- 신발외장 (footwear) ---
    "SHOES_STD_01": ("Reinforced Plastic Walkers", "[T=3 Standard] Hard industrial resin in the toe cap prevents toe-bone lock-up errors."),
    "SHOES_STD_02": ("Grip-Reinforced Combat Boots", "[T=3 Standard] Helps you act first (INIT) on oil-slicked factory floors and slippery ghost node tiles."),
    "SHOES_STD_03": ("Steel-Studded Desert Boots", "[T=3 Standard] Eliminates micro-slips on sand tiles, slowing hunger drain."),
    "SHOES_STD_04": ("Thick Industrial Geiger Acid Boots", "[T=3 Standard] Reduces contamination stack ticks by -1 when entering acid pools or molten radioactive basin tiles."),
    "SHOES_STD_05": ("Cybernetic Power-Valve Servo Boots", "[T=3 Standard] A small return-servo gimmick in the heel raises your initiative index in real time."),
    "SHOES_STD_06": ("Ballistic-Patch Hybrid Sneakers", "[T=3 Standard] Light canvas sneakers patched with Kevlar, balancing mobility and defense."),
    "SHOES_STD_07": ("Tin-Lined Scrap Shoes", "[T=3 Standard] Negates recoil damage from failing to disarm the nail traps covering 95% of the barren ground."),
    "SHOES_STD_08": ("Screw-Studded Full-Leather Boots", "[T=3 Standard] Thick cowhide boots with 30 small industrial screws driven in for maximum grip."),
    "SHOES_STD_09": ("Stretch-Film Reinforced Work Shoes", "[T=3 Standard] Worn hiking boots rolled in high-strength epoxy and film for durability."),
    "SHOES_STD_10": ("Drone-Skid Frame Sandals", "[T=3 Standard] Uses the spring of a wrecked drone's landing skid to boost the effective value of Agility."),
    # --- 목걸이 (necklace) ---
    "NECK_STD_01": ("Soldered Chipset Pendant", "[T=3 Standard] A necklace of several old radio chipsets soldered onto zinc wire and neatly draped."),
    "NECK_STD_02": ("Machined Solder Washer Choker", "[T=3 Standard] A choker of 20 brass grounding washers set tightly into a leather band to guard the neck's power lines."),
    "NECK_STD_03": ("Drone Aperture Lens Ring", "[T=3 Standard] A gadget pendant made from a recon drone's unbroken zoom lens barrel that aids sensor computation."),
    "NECK_STD_04": ("Resistance Wheezing Voicebox Choker", "[T=3 Standard] An analog wireless mic element wired to the throat, raising radio link sensitivity with your team."),
    "NECK_STD_05": ("Subcontractor Plastic ID Necklace", "[T=3 Standard] A security ID choker from the corporate lower tiers. Gives text hints on entry conditions for certain ghost nodes."),
    "NECK_STD_06": ("High-Voltage Overload Fuse Pendant", "[T=3 Standard] Three glass tube fuses from substation ruins strung on silver wire, aiding computational contamination resistance."),
    "NECK_STD_07": ("Bio Hound Coolant Choker", "[T=3 Standard] A mech-beast's cooling line wrapped around the neck to curb neural heat buildup when cybernetics run."),
    "NECK_STD_08": ("Cyberdeck Mesh Ground Band", "[T=3 Standard] A leather nape pad that absorbs micro-surges from a running cyberdeck to prevent brain damage."),
    "NECK_STD_09": ("Series Rifle Casing Necklace", "[T=3 Standard] Spent 5.56mm casings, cleanly polished in a Scrap Coalition workshop, lined up on a leather cord."),
    "NECK_STD_10": ("Triple-Layer Can-Tab Necklace", "[T=3 Standard] A hundred-odd aluminum can tabs woven like chain mail to protect the collarbones."),
    # --- 반지 (ring) ---
    "RING_STD_01": ("Machined Solder Washer Ring", "[T=3 Standard] A standard ring: a brass washer from a precision switchboard, its bore carefully ground to fit the finger."),
    "RING_STD_02": ("Titanium Hound Fang Ring", "[T=3 Standard] A Resistance token ring: a mech-beast's broken fang engraved with darknet ID codes."),
    "RING_STD_03": ("Precision Hex Nut Ring", "[T=3 Standard] A rusty factory nut shaped with a spanner, stripped of rust, and silver-plated."),
    "RING_STD_04": ("Fluorescent Fiber Knot Loop", "[T=3 Standard] A ring of fiber strands from a severed comms line, finely bound to carry a faint current."),
    "RING_STD_05": ("Aluminum Volume-Knob Gadget Ring", "[T=3 Standard] A cyberdeck's packet output dial pried off and modded into a finger switch ring."),
    "RING_STD_06": ("Precision Return-Spring Loop", "[T=3 Standard] A gadget ring that gives slight tension feedback when you enter a stepped stat-diminishing bracket."),
    "RING_STD_07": ("Mercury-Cell LED Ring", "[T=3 Standard] A ring with a tiny diode bulb and cell that lights keypads in dark node server rooms."),
    "RING_STD_08": ("Expired Corporate Smart-Chip Signet", "[T=3 Standard] An info-engineer's ring soldered from an expired RFID chip once used to open megacorp door locks."),
    "RING_STD_09": ("Tri-Color Composite Wire Shield Ring", "[T=3 Standard] A grounding ring of three twisted wires that stops power leaks at every cybernetic knuckle."),
    "RING_STD_10": ("Disposable Bypass Proxy Key Ring", "[T=3 Standard] A ring with a smart element that guarantees one successful virtual safehouse data laundering log."),
    # --- 특화부품 (custom_part) ---
    "PART_STD_01": ("Standard Magnetic Accelerator", "[T=3 Standard] [Combat] Unique power index alpha +2 permanently for main weapon basic skills / [Penalty] Hunger/thirst always drain +2 faster at the end of each firing turn."),
    "PART_STD_02": ("Reinforced Dynamic Heatsink", "[T=3 Standard] [Net] Compute acceleration +3% on successful [Grid Intrude] / [Penalty] In-city firewall trace index (Alert) +5 every turn while active."),
    "PART_STD_03": ("Servo Gimmick Clock Charger", "[T=3 Standard] [Combat] Crit chance +5% permanently / [Penalty] Base physical defense fixed at -8."),
    "PART_STD_04": ("Copper-Alloy Precision Resistor Coil", "[T=3 Standard] [Net] 10% chance to refund 1 RAM when using RAM-cost skills / [Penalty] Max RAM forcibly locked at -1 until the combat ends."),
    "PART_STD_05": ("Optical Scan Frequency Tip", "[T=3 Standard] [Utility] +1.0% to the 1% ghost data box detection rate when searching the field / [Penalty] Mech-beast raid chance x1.2 when moving across field tiles."),
    "PART_STD_06": ("Hydraulic Lubricant Injector", "[T=3 Standard] [Combat] [Bio Reap] trigger chance +4% permanently / [Penalty] Inventory carry weight limit permanently locked at -5kg."),
    "PART_STD_07": ("Bypass Proxy Encryption Wrapper", "[T=3 Standard] [Net] [Protocol Glitch] log forgery success +4% permanently / [Penalty] +10 computational contamination stack on every failed forgery attempt."),
    "PART_STD_08": ("Plasma Overclock Nozzle", "[T=3 Standard] [Combat] Main weapon final damage multiplier +7% permanently / [Penalty] Beyond 10 skill uses, the pattern exposure penalty rises from 5% to 8% per use."),
    "PART_STD_09": ("Memory Dump Accelerator Pack", "[T=3 Standard] [Net] Status effect and elemental resistance +6% permanently / [Penalty] Penalty-free flee option completely sealed when facing defeat."),
    "PART_STD_10": ("Drone Gyro Velocity Sensor", "[T=3 Standard] [Combat] Initiative index (INIT) +10 permanently / [Penalty] Base axis of the x100 Vitality calculation fixed at -200."),

    # ===== [2등급: 정제 (Refined)] =====
    # --- 주무기 (main_weapon) ---
    "WEAPON_REF_01": ("Bio-Core Ripper Knife", "[T=2 Refined] A mutant mech-beast's cutting sawblade overlaid onto cybernetic control lines, tearing machine and flesh apart at once."),
    "WEAPON_REF_02": ("Frequency Shredder Spanner", "[T=2 Refined] An engineer's bludgeon that corrupts an enemy's internal frequency to overload and blow its logic circuits directly."),
    "WEAPON_REF_03": ("Neurotoxic Plasma Gun", "[T=2 Refined] A gun whose barrel is a discharge membrane harvested from a beast's corpse, emitting bio-contamination packet damage."),
    "WEAPON_REF_04": ("Hound Titanium Jaw-Arm", "[T=2 Refined] An extreme crushing device linking a canine mech-beast's hydraulic jaw to the underside of a cybernetic arm."),
    "WEAPON_REF_05": ("Resonant Pile Bunker", "[T=2 Refined] A heavy weapon fusing a compressed gasoline pack with a beast's heat vent to annihilate base armor in one strike."),
    "WEAPON_REF_06": ("Hybrid Arc Blade", "[T=2 Refined] A sword that reads the resonance of Agility and Vitality to dynamically tune the bio-current flowing through its blade."),
    "WEAPON_REF_07": ("Tactical Frequency Revolver", "[T=2 Refined] A custom magnetic pistol that further reduces enemy effective defense when linked with Signal Trace."),
    "WEAPON_REF_08": ("Overclock Ax", "[T=2 Refined] A great axe that turns the recoil energy of an active Overclock into forward momentum."),
    "WEAPON_REF_09": ("Refined EM Shredder Cannon", "[T=2 Refined] A max-power model: under the damage formula, its burst of true damage converges on a fixed peak."),
    "WEAPON_REF_10": ("Bio-Ripper Ultrasonic Pistol", "[T=2 Refined] A ballistic pistol with micro-vibration elements from dismantled corpses set into the firing pin, multiplying its rate of fire."),
    # --- 사이버덱 (cyberdeck) ---
    "DECK_REF_01": ("Bio Hound Reverse-Engineered Deck", "[T=2 Refined] A cyberdeck using a beast's artificial spinal network as its motherboard, vastly improving RAM recovery."),
    "DECK_REF_02": ("Refined Backdoor Link v3", "[T=2 Refined] A hacking rig that artificially delays the trigger calculations of the in-city firewall trace index (Alert)."),
    "DECK_REF_03": ("Grid Injection Master", "[T=2 Refined] A compute unit that forcibly cuts the base RAM cost of the unique skill [Grid Intrude] by 1."),
    "DECK_REF_04": ("Protocol Error Emitter", "[T=2 Refined] A cyberdeck that constantly spreads backdoor glitch logs into the reality-law code projected by the Master AI."),
    "DECK_REF_05": ("Hybrid Signal Processor", "[T=2 Refined] Amplifies the chance to extract ghost data boxes in the field when Intellect and Agility are within 3 of each other."),
    "DECK_REF_06": ("Reality Distortion Script Pack", "[T=2 Refined] A deck that warps the output of a successful [Protocol Glitch], raising the chance to induce enemy friendly fire."),
    "DECK_REF_07": ("Automated Swarm Drone Control Deck", "[T=2 Refined] A rig that dynamically raises the range and overclock acceleration of sentry turrets and their control algorithms."),
    "DECK_REF_08": ("Node-Laundering Proxy Deck", "[T=2 Refined] Delays the onset of the Wanted debuff incurred when a virtual safehouse refresh cycle fails."),
    "DECK_REF_09": ("Beast Compute-Core Extraction Deck", "[T=2 Refined] A device that bypasses a mech-beast's intelligence core into a cyberdeck operator to speed up packet scans."),
    "DECK_REF_10": ("Darknet Anarchist Link", "[T=2 Refined] A warped compute unit that logically smooths over the Bureau reputation decay penalty during fights inside Neo Arc."),
    # --- 의체부품 (cybernetic_parts) ---
    "CYBER_REF_01": ("Beast-Harvested Bio Spine", "[T=2 Refined] A cybernetic implant wiring a mech-beast's central spine into your body, permanently boosting the base stat efficiency function f(A)."),
    "CYBER_REF_02": ("Neuro-Synced Titanium Skeleton", "[T=2 Refined] Titanium framing precisely fused with organic artificial nerves, encoding base physical DEF and Vitality together."),
    "CYBER_REF_03": ("Organic Fusion Cyber-Arm", "[T=2 Refined] A cybernetic arm that tracks the hybrid value of Agility and Vitality to raise part-durability shredding on [Bio Reap]."),
    "CYBER_REF_04": ("Nano Carbon-Fiber Heart", "[T=2 Refined] A high-end artificial organ that senses bodily fatigue and permanently optimizes hunger/thirst drain weighting."),
    "CYBER_REF_05": ("Sensor-Overclock Cyber-Eye", "[T=2 Refined] An eye that scans enemy weak points and wiring logs, turning your damage into a lasting defense-down debuff."),
    "CYBER_REF_06": ("Hydraulic High-Torque Femur Frame", "[T=2 Refined] Combat Force leg cybernetics that fill the limits of skill-capped 70% growth with raw hardware output."),
    "CYBER_REF_07": ("Firewall-Aware Nape Implant", "[T=2 Refined] A nape implant that cancels and vents the brain-damage filter value from cyberdeck overload as a physical shockwave."),
    "CYBER_REF_08": ("Beast-Plate Grafted Sternum", "[T=2 Refined] A part that synergizes with heavy-armor protocols to aid real-time regeneration of base barrier durability."),
    "CYBER_REF_09": ("Fiber-Linked Brainwave Amplifier", "[T=2 Refined] An implant that accelerates the available RAM formula in real time, extending how many Net Force skills you can chain."),
    "CYBER_REF_10": ("Servo-Link Joint Motor Pack", "[T=2 Refined] Refines the rotation of limiter-free joint motors to help win first-turn checks (INIT)."),
    # --- 등 장비 (back_gear) ---
    "BACK_REF_01": ("Overclock Cooler Pack", "[T=2 Refined] A high-output radiator that flash-freezes compute overload in cybernetics and cyberdecks with a liquid nitrogen loop."),
    "BACK_REF_02": ("Bio-Fuel Injector Tank", "[T=2 Refined] A pack that injects liquid energy refined from wasteland beast corpses in real time, saving bodily resources while moving."),
    "BACK_REF_03": ("Dynamic Frequency Jamming Discharger", "[T=2 Refined] Jams enemy mech-beasts' radio receivers while crossing the field, minimizing ambush rates."),
    "BACK_REF_04": ("Light Plasma Battery Cell", "[T=2 Refined] A power pack that holds the power signal index to zero-sum when deploying sentry turrets and holding base barriers."),
    "BACK_REF_05": ("Wireless Matrix Extension Antenna", "[T=2 Refined] A mast that constantly tunes your virtual safehouse's camouflage index to help evade the Master AI's tracking algorithms."),
    "BACK_REF_06": ("Hybrid Ammo Composite Rig", "[T=2 Refined] A harness that mounts weapons and tools on both sides, helping meet the conditions of hybrid-style secret quests."),
    "BACK_REF_07": ("Geiger-Linked Backpack", "[T=2 Refined] A backpack that physically blocks environmental contamination stacks from accruing in molten radioactive basins."),
    "BACK_REF_08": ("Swarm Drone Maintenance Auto-Rack", "[T=2 Refined] A hard-shell pack that dynamically supports turret skill trigger rates and crit multiplier weighting."),
    "BACK_REF_09": ("Cybernetic Weight-Distribution Servo Harness", "[T=2 Refined] A rig that vastly raises carry weight, removing weight limits when farming high-tier relic gear."),
    "BACK_REF_10": ("Scavenger Master Tactical Pack", "[T=2 Refined] Adds a fixed amount to dropped resources when you successfully extract a ghost data box deep in the barrens."),
    # --- 안면 (face) ---
    "FACE_REF_01": ("Optical Scan HUD Goggles", "[T=2 Refined] Goggles that fine-tune crit chance weighting during initiative and first-turn checks in combat."),
    "FACE_REF_02": ("Beast-Plate Reinforced Helmet", "[T=2 Refined] A helm press-molded from mech-beast hardware shell to fit the skull, nullifying headshot crit damage."),
    "FACE_REF_03": ("Firewall Counter-Trace Monologue Mask", "[T=2 Refined] A full-face mask that precisely filters the firewall trace acceleration bracket while you remain on Neo Arc city tiles."),
    "FACE_REF_04": ("Variable-Aperture Bio Sensor", "[T=2 Refined] A monocle that synergizes with Agility's effective value function f(A) to push circuit-sniping chance to its limit."),
    "FACE_REF_05": ("Refined Insulated Gas Visor", "[T=2 Refined] A chemical-warfare mask that steadily raises the denominator constant of the status and elemental resistance formula."),
    "FACE_REF_06": ("Hybrid Resonance Spectrum HUD", "[T=2 Refined] Goggles that dynamically optimize parsing of the [Hybrid Resonance] trait, which triggers when all three stats are equal."),
    "FACE_REF_07": ("Cyber Security Squad Filter Mask", "[T=2 Refined] A gas mask stolen from a corporate cleanup squad that blocks the buildup of virtual compute contamination stacks."),
    "FACE_REF_08": ("Signal Trace Monocular HUD", "[T=2 Refined] A visual device that links hidden resource node detection and crit multiplier amplification in real time."),
    "FACE_REF_09": ("Leather-Flap Tactical Guard", "[T=2 Refined] A mask that reduces enemy ambush damage weighting by a percentage during constant human raider raids."),
    "FACE_REF_10": ("Nano-Lattice Face Guard Gadget", "[T=2 Refined] Protects the bio-cybernetic control lines around the mouth, preserving the [Bio Reap] trigger chance bonus."),
    # --- 상의외장 (top) ---
    "TOP_REF_01": ("Canine-Beast Hide Ballistic Vest", "[T=2 Refined] A top that builds the frame of base physical DEF from a Bio Hound's tough hide precisely fused with Kevlar."),
    "TOP_REF_02": ("Bioware Sync Coat", "[T=2 Refined] A special coat whose lining's neural elements sync with how efficiently you invest the 30% free AP into Vitality."),
    "TOP_REF_03": ("Refined Duralumin Plate Vest", "[T=2 Refined] A breastplate of scrapyard aircraft alloy, heat-refined to raise base physical defense in steps."),
    "TOP_REF_04": ("Darknet Anarchist Leather Coat", "[T=2 Refined] Garb of the terrorists who paralyze the main city's grid. Eases the Wanted debuff penalty."),
    "TOP_REF_05": ("Mad Engineer Tactical Workwear", "[T=2 Refined] Clothing that locks the random variance of assembling beast corpses and junk to a stable high point."),
    "TOP_REF_06": ("Conformist Bioware Suit", "[T=2 Refined] A corporate subcontractor coat that further amplifies displayed Vitality while your Bureau reputation weight is positive."),
    "TOP_REF_07": ("Bastion Garrison Captain Heavy Armor", "[T=2 Refined] A top with a built-in algorithm that steals enemy weapon power back on a successful base raid log."),
    "TOP_REF_08": ("Static-Absorbing Mesh Vest", "[T=2 Refined] Clothing that mathematically delays the turn at which brain damage and system shock stacks reach 100."),
    "TOP_REF_09": ("Hybrid Resonance Tactical Jacket", "[T=2 Refined] Fully preserves your main unique skill's weight conversion rate when all three stats are evenly balanced."),
    "TOP_REF_10": ("Scavenger Leader Hard Chain Mail", "[T=2 Refined] A coat of steel rings and beast bone shards in a composite array that inflicts a shredding penalty back on attackers."),
    # --- 하의외장 (bottom) ---
    "BOTTOM_REF_01": ("Mid-Tier Tactical Light Pants", "[T=2 Refined] Pants that tune friction in lower-body cybernetic drives to near zero, accelerating your initiative index (INIT)."),
    "BOTTOM_REF_02": ("Beast-Plate Thigh Guards", "[T=2 Refined] Hardcore pants that physically offset enemy mech-beasts' defense penetration."),
    "BOTTOM_REF_03": ("Radioactive Basin Pants", "[T=2 Refined] Pants that push resistance to the contamination stacks that build 1 at a time in the deep wasteland to its limit."),
    "BOTTOM_REF_04": ("VR Camouflage Pattern Pants", "[T=2 Refined] Special pants that forcibly lower the firewall trace acceleration formula while in Neo Arc slum nodes."),
    "BOTTOM_REF_05": ("Hybrid Tuner Tactical Pants", "[T=2 Refined] Adds to the master bonus weight of the skill power formula when Vitality and Agility are within 3 of each other."),
    "BOTTOM_REF_06": ("Hydraulic Cylinder Guard Leggings", "[T=2 Refined] Pants that prevent wear on hydraulic leg cybernetics, maximizing reduction of hunger/thirst drain."),
    "BOTTOM_REF_07": ("Darknet Infiltrator Cargo", "[T=2 Refined] Pants that nullify the 30% plunder penalty on hidden resources when a forced extraction (smuggling) succeeds."),
    "BOTTOM_REF_08": ("High-Voltage Insulated Mesh Overalls", "[T=2 Refined] Special overalls that guard the threshold of the compute contamination (RAM locked at 0) penalty with a mathematical barrier."),
    "BOTTOM_REF_09": ("Junkyard Master Artisan Pants", "[T=2 Refined] Pants that optimize the effective value conversion of Intellect and Agility at the limits of scrap refining and makeshift weapon crafting."),
    "BOTTOM_REF_10": ("Titanium-Lattice Combat Pants", "[T=2 Refined] Off-spec pants for scavenger assault troops that physically refuse lower-body severing logs."),
    # --- 신발외장 (footwear) ---
    "SHOES_REF_01": ("Shock-Absorbing Servo Boots", "[T=2 Refined] Servo bearings in the soles apply accelerating torque on turn changes, permanently aiding initiative."),
    "SHOES_REF_02": ("Bio Hound Claw Grip Shoes", "[T=2 Refined] Beast claw elements set into the soles prevent survival drain from slipping on desert tiles."),
    "SHOES_REF_03": ("Refined Acid-Proof Geiger Boots", "[T=2 Refined] Contamination-zone boots that precisely damp environmental contamination stack ticks down to the decimal."),
    "SHOES_REF_04": ("Limiter-Off Berserker Shoes", "[T=2 Refined] Disables joint-motor safeties and wires in the spinal nerves directly, inducing enemy turn-freeze logs on a successful ambush."),
    "SHOES_REF_05": ("Hybrid Resonance Light Walkers", "[T=2 Refined] Shoes that boost the initiative index (INIT) formula to its limit when all three stats are equal."),
    "SHOES_REF_06": ("Firewall-Bypass Packet Shoes", "[T=2 Refined] Boots that offset the tripled in-city ambush rate penalty with virtual frequency camouflage."),
    "SHOES_REF_07": ("Bastion Construction Captain Safety Boots", "[T=2 Refined] Heavy-armor engineer shoes that synergize with base construction and defense cost reduction formulas."),
    "SHOES_REF_08": ("Escape Protocol Accelerator Boots", "[T=2 Refined] Raises the chance a guerrilla infiltrator can instantly flee combat without penalty."),
    "SHOES_REF_09": ("Titanium-Outsole Tactical Boots", "[T=2 Refined] Shoes that forcibly pin your effective defense at its peak in the damage formula for failed trap disarms."),
    "SHOES_REF_10": ("Drone Gyro Velocity Shoes", "[T=2 Refined] Boots that mathematically delay the overload bracket of Agility's effective value function f(A)."),
    # --- 목걸이 (necklace) ---
    "NECK_REF_01": ("Bio-Signal Stabilizer Necklace", "[T=2 Refined] A trinket that permanently improves base infrastructure recovery by +2 per turn as physical/compute contamination ticks accrue."),
    "NECK_REF_02": ("Quantum-Weighted Stabilizer Choker", "[T=2 Refined] A choker that forcibly syncs the resonance weight coefficient of hybrid skills to its maximum of 1.0."),
    "NECK_REF_03": ("Hound Spinal Fluid Choker", "[T=2 Refined] Syncs a mech-beast's coolant tube signals to the neck's power lines, preventing wear on your cybernetic nervous system."),
    "NECK_REF_04": ("Cyberdeck Surge-Absorbing Pendant", "[T=2 Refined] Gently deflects the system shock recoil from the Master AI firewall during direct net access."),
    "NECK_REF_05": ("Secret NPC Trust Seal Necklace", "[T=2 Refined] A chain that claims the final reward of hidden jobs a secret NPC opens when your main stats are within 3 of each other."),
    "NECK_REF_06": ("Dynamic Reputation Equilibrium Choker", "[T=2 Refined] Optimizes the reputation weight margin of the damage formula as faction reputation shifts."),
    "NECK_REF_07": ("Built-In Geiger Counter Chain", "[T=2 Refined] Helps keep hunger/thirst drain at its minimum integer floor when entering hazardous environment tiles."),
    "NECK_REF_08": ("Tier-0 Relic Binding Dampener", "[T=2 Refined] Slightly eases the rapid offline survival resource depletion penalty from stacking endgame relic gear."),
    "NECK_REF_09": ("Refined Fuse Element Pendant", "[T=2 Refined] Raises the correction chance when circuits overheat and fail from excessive skill point (SP) injection."),
    "NECK_REF_10": ("Seamless Voicebox Mesh Choker", "[T=2 Refined] A refined frequency choker used by anarchist virtual terrorists solely to launder their comms."),
    # --- 반지 (ring) ---
    "RING_REF_01": ("Virtual Encryption Key Ring", "[T=2 Refined] A hacker's refined ring that mathematically amplifies firewall-bypass efficiency when hacking ghost nodes."),
    "RING_REF_02": ("Hybrid Resonance Loop", "[T=2 Refined] Supports the level-cap extension curve of unique skills when the three base stats are in stable symmetry."),
    "RING_REF_03": ("Titanium Hound Fang Signet", "[T=2 Refined] A signet ring permanently engraved with a bonus to revealing part-durability shred logs when striking mech-beasts."),
    "RING_REF_04": ("Aluminum Dial Knob Ring v4", "[T=2 Refined] A heavily modded ring with a 10% chance to instantly refund compute resources spent on RAM-cost skills."),
    "RING_REF_05": ("Refined Corporate Smart-Chip Ring", "[T=2 Refined] A ring that fools security squads when you forcibly extract resources from sealed data vaults inside Neo Arc."),
    "RING_REF_06": ("Disposable Bypass Proxy Key Loop", "[T=2 Refined] Delays when the Master AI's security protocols fully neutralize you for holding the same node too long."),
    "RING_REF_07": ("Micro-Current Triple-Bound Loop", "[T=2 Refined] A ring that holds power-source overload variance to a minimum of 1 when cybernetic joint limiters are off."),
    "RING_REF_08": ("Singularity Micro-Loop", "[T=2 Refined] Slightly restores efficiency in the paralysis bracket (stat above 25) of the stepped weight-falloff function f(A)."),
    "RING_REF_09": ("Fluorescent Fiber-Knot Signet", "[T=2 Refined] A ring that removes visual fatigue when parsing a cyberdeck's base RAM and compute throughput."),
    "RING_REF_10": ("Seamless Proxy Encryption Ring", "[T=2 Refined] Supports the system for penalty-free teleport and escape logs when facing defeat in combat."),
    # --- 특화부품 (custom_part) ---
    "PART_REF_01": ("High-Output Bio Accelerator Module", "[T=2 Refined] [Combat] Always gain first strike while unique skill [Overclock] is active / [Penalty] Contamination resistance RES locked at 0% during combat."),
    "PART_REF_02": ("Frequency Layering Amplifier", "[T=2 Refined] [Combat] Base crit multiplier permanently raised to 2.0 on a successful [Signal Trace] / [Penalty] Flee command locked until that combat ends."),
    "PART_REF_03": ("Virtual Tactical Overlay Patch", "[T=2 Refined] [Net] Wide-area virus packets always pierce an extra 15 effective defense on every mech-beast / [Penalty] Max RAM locked by 1 per activation turn."),
    "PART_REF_04": ("Ripperdoc Grid Sync Chip", "[T=2 Refined] [Combat] Survival absorbed by [Bio Reap] always +10 / [Penalty] Inventory weight limit fixed at -5kg."),
    "PART_REF_05": ("Grid Hunter Reverse-Engineered Nozzle", "[T=2 Refined] [Combat] Main weapon final damage multiplier +10% permanently / [Penalty] Beyond 10 consecutive skills, the pattern exposure penalty rises to 8% per use."),
    "PART_REF_06": ("Void Injector Base Pump", "[T=2 Refined] [Net] Breaks the system cap on [Protocol Glitch] success, raising it dynamically up to 75% / [Penalty] Brain damage from a failed forgery +200%."),
    "PART_REF_07": ("Titan Crusher Pulverizer Module", "[T=2 Refined] [Combat] Hits on mech-beasts apply a debuff that permanently cuts their base physical defense by 15% / [Penalty] Your initiative index (INIT) fixed at -10."),
    "PART_REF_08": ("Sentry Infra Auto Tune-Up", "[T=2 Refined] [Net] Turret skill trigger rate and range formulas converge on the peak of the Intellect function / [Penalty] Base barrier durability -50 immediately when a turret is destroyed."),
    "PART_REF_09": ("Smuggler Packet Compression Wrapper", "[T=2 Refined] [Net] +5% chance to obtain high-value titanium scrap and resources on victory / [Penalty] Neo Arc firewall trace index +4 extra every turn."),
    "PART_REF_10": ("Bio Reap Power Surge Chip", "[T=2 Refined] [Combat] A successful first-turn ambush freezes (skips) all enemies' turns for 1 turn / [Penalty] Hunger/thirst drain x1.5 for the combat session while active."),

    # ===== [1등급: 기업제 (Corporate)] =====
    # --- 주무기 (main_weapon) ---
    "WEAPON_CORP_01": ("Arasaka Nano Laser Katana", "[T=1 Corporate] An endgame corporate blade lined with dense laser particles, slicing cleanly through barriers and cybernetics at the molecular level."),
    "WEAPON_CORP_02": ("Militech Service Railgun v9", "[T=1 Corporate] The hypervelocity cannon Neo Arc security uses to purge the barrens, a sniper weapon computing the pinnacle of true damage."),
    "WEAPON_CORP_03": ("Orbital Air Plasma Blaster", "[T=1 Corporate] A heavy weapon that compresses an electromagnetic field into a sphere and fires it, forcibly ignoring 40% of enemy final effective defense."),
    "WEAPON_CORP_04": ("Biotechnica Neurotoxin Emitter", "[T=1 Corporate] A tactical weapon that injects 30 paralysis stacks per turn directly into the organic tissue inside enemy cybernetics, freezing their hardware."),
    "WEAPON_CORP_05": ("Kang Tao Micro Smart Pistol", "[T=1 Corporate] A guided pistol that, linked with Agility's value conversion, chews through enemy evasion formulas and guarantees a 100% hit log."),
    "WEAPON_CORP_06": ("Trauma Team HF Cutting Scalpel", "[T=1 Corporate] A high-tech melee weapon that maximizes cybernetic severing chance, disabling and destroying a human soldier's main weapon in a single strike."),
    # --- 사이버덱 (cyberdeck) ---
    "DECK_CORP_01": ("Neo Arc Security Agent Deck", "[T=1 Corporate] A cyberdeck with backdoor protocols to the Master AI main server installed under legal license, dropping enemy firewalls at light speed."),
    "DECK_CORP_02": ("NeoNet Quantum Mainframe Core", "[T=1 Corporate] Brute-force data bank hardware that adds a flat +8 to the base of Net Force's available RAM formula."),
    "DECK_CORP_03": ("Militech Tactical Firewall Deck", "[T=1 Corporate] A deck that constantly blocks 50% of beasts' digital counter-hack (brain damage and system shock) packets, protecting your fragile body."),
    "DECK_CORP_04": ("Microtech High-Speed Packetware", "[T=1 Corporate] Forcibly locks base hacking compute acceleration at max (+50%) regardless of your Intellect investment."),
    "DECK_CORP_05": ("Biotechnica Organic Circuit Deck", "[T=1 Corporate] A bio-assimilating deck that converts 30% of RAM spent on a successful [Grid Intrude] back into displayed Vitality in real time."),
    "DECK_CORP_06": ("Arasaka Darknet Protocol Deck", "[T=1 Corporate] A cyberdeck that adds the Intellect function's peak multiplier to [Protocol Glitch] forgery odds, supercharging glitch performance."),
    # --- 의체부품 (cybernetic_parts) ---
    "CYBER_CORP_01": ("Trauma Team Bioware Engine", "[T=1 Corporate] Cybernetics whose nanobots repair organic signals every second, pushing hunger/thirst drain reduction to the system cap."),
    "CYBER_CORP_02": ("Militech Enhanced Strength Servo Arm", "[T=1 Corporate] A military heavy-armor motor frame. Breaks the soft-cap threshold of Combat Force's unique skill level curve to extend output."),
    "CYBER_CORP_03": ("Arasaka Nano Reflex Network", "[T=1 Corporate] A fiber-optic nervous system implanted along the spine. Negates the efficiency drop in Agility's f(A) overload bracket (stat 15)."),
    "CYBER_CORP_04": ("Orbital Bio Radiation Filter Core", "[T=1 Corporate] A high-end artificial organ that always cuts physical contamination ticks by a flat -20 per turn on irradiated basin tiles."),
    "CYBER_CORP_05": ("Kang Tao Intelligent Compute Cortex", "[T=1 Corporate] Cybernetics that preset-lock the ancient relic appraisal and analysis success formula at the system cap of 95%."),
    "CYBER_CORP_06": ("Biotechnica Organic Artificial Heart", "[T=1 Corporate] An engine that always injects a 1.5x Vitality coefficient bonus into the base max-Vitality formula on level-up."),
    # --- 등 장비 (back_gear) ---
    "BACK_CORP_01": ("Technocracy Jet Booster", "[T=1 Corporate] A back-mounted accelerator that vents high-pressure gas to explosively speed up the initiative index (INIT) and offset field ambush rates."),
    "BACK_CORP_02": ("Nano-Carbon Expanding Logistics Pack", "[T=1 Corporate] A bag that inflates the carry weight formula's variables, erasing weight penalties from stacking heavy corporate gear."),
    "BACK_CORP_03": ("Corporate Infinite Cooling Tower", "[T=1 Corporate] A dynamic cooling pack that artificially launders 1 pattern-exposure stack every 3 turns when you spam one unique skill."),
    "BACK_CORP_04": ("Tactical Guided Drone Rack", "[T=1 Corporate] A pack that pins the final displayed damage of an automation engineer's [Sentry Infra] turrets at the peak, without variance."),
    "BACK_CORP_05": ("Orbital Air Energy Accelerator Cell", "[T=1 Corporate] A backpack that instantly freezes the consumed power signal index to 0 when you hold a base barrier or repel a raid."),
    "BACK_CORP_06": ("Microtech Signal Deflector", "[T=1 Corporate] A gadget that forcibly delays, by mathematical model, the Master AI's full security-protocol patch cycle while squatting on a virtual safehouse node."),
    # --- 안면 (face) ---
    "FACE_CORP_01": ("Bureau Hologram Visor", "[T=1 Corporate] A face gadget synced with Agility-derived stats that locks the crit chance formula at its cap of 75%."),
    "FACE_CORP_02": ("Arasaka Heavy Armor Hyper Helmet", "[T=1 Corporate] Issued upon reaching friendly Bureau reputation (+500 or more). Completely erases the tripled ambush rate penalty in the barrens."),
    "FACE_CORP_03": ("Militech Tactical Full-Face Gas Mask", "[T=1 Corporate] A mask that syncs the gear weight coefficient to its peak in status and elemental resistance checks, preventing contamination overflow."),
    "FACE_CORP_04": ("Kang Tao Variable Multifocal Glasses", "[T=1 Corporate] Smart glasses that restore efficiency in Intellect's paralysis bracket (stat above 25) to around 50%."),
    "FACE_CORP_05": ("Orbital Air Pressurized HUD Visor", "[T=1 Corporate] A precision gadget that always adds a +0.3 bonus margin to the crit multiplier axis on first-turn checks."),
    "FACE_CORP_06": ("Biotechnica Cell Analysis Goggles", "[T=1 Corporate] Goggles that bind a permanent +6% correction constant directly into the [Bio Reap] trigger chance formula."),
    # --- 상의외장 (top) ---
    "TOP_CORP_01": ("Bureau Security Nano-Fiber Suit", "[T=1 Corporate] The Bureau elite's standard top. Ultra-dense ballistic weave that reliably keeps displayed Vitality in the tens of thousands."),
    "TOP_CORP_02": ("Executive Firewall Long Coat", "[T=1 Corporate] High-end outerwear that syncs your virtual safehouse security grade inside Neo Arc to top priority, dominating survival stability in the city."),
    "TOP_CORP_03": ("Arasaka Military Nano-Plate Cuirass", "[T=1 Corporate] Armor that blows up the fixed constant of the physical defense formula, pushing mutant beast damage down to the minimum of 1."),
    "TOP_CORP_04": ("Militech Cleanup Squad Heavy Guardian", "[T=1 Corporate] An armored top that accelerates real-time barrier repair when barrens raiders hit your base under the reputation zero-sum rule."),
    "TOP_CORP_05": ("Orbital Air Shock-Absorbing Tactical Suit", "[T=1 Corporate] A top that forcibly cuts the final damage weight P by 20% when a Titan Crusher's native penetration (80) strike lands."),
    "TOP_CORP_06": ("Kang Tao Hybrid Resonance Vest", "[T=1 Corporate] A custom vest that controls imbalance among your three base stats in real time to help meet the [Golden Ratio Harmonizer] Signal-Locked Trait."),
    # --- 하의외장 (bottom) ---
    "BOTTOM_CORP_01": ("Executive Tactical Pants", "[T=1 Corporate] Pants that zero out lower-body cybernetic motor power draw, optimizing hunger/thirst drain while crossing the wasteland."),
    "BOTTOM_CORP_02": ("Arasaka Security Guard Nano Jeans", "[T=1 Corporate] Tactical pants that mathematically block the trigger turn of RAM-leak contamination stacks during Neo Arc virtual node hacking sessions."),
    "BOTTOM_CORP_03": ("Militech Special Agent Insulated Cargo", "[T=1 Corporate] Pants that permanently refuse the fatal error penalty where system shock reaches 100 and locks available RAM at 0."),
    "BOTTOM_CORP_04": ("Orbital Air Mobility Accelerator Pants", "[T=1 Corporate] Pants that limiter-lock the base evasion formula, an Agility-derived stat, at its cap of 50%."),
    "BOTTOM_CORP_05": ("Biotechnica Cell-Refining Overalls", "[T=1 Corporate] Pants that erase status ticks from debuff attacks down to the decimal while you are in danger with survival stats above 90%."),
    "BOTTOM_CORP_06": ("Kang Tao Tactical Hydraulic Pants", "[T=1 Corporate] Pants that maximize the efficiency of investing the 30% free AP into Agility, securing Combat Force's ambush turn-freeze success rate."),
    # --- 신발외장 (footwear) ---
    "SHOES_CORP_01": ("Maglev Mobility Shoes", "[T=1 Corporate] Shoes with maglev nano-motors that ignore ground friction entirely, adding an unrivaled multiplier to the initiative index (INIT) formula."),
    "SHOES_CORP_02": ("Arasaka Nano Silent Tactical Walkers", "[T=1 Corporate] Shoes that fully block noise/power signal buildup while moving across field tiles, bypassing the anti-farming mutant beast raid clause."),
    "SHOES_CORP_03": ("Militech Heavy Assault Safety Boots", "[T=1 Corporate] Steel walkers that activate a knockback immunity log with 100% chance on the opening first-turn check of combat."),
    "SHOES_CORP_04": ("Orbital Air Phase-Sync Boots", "[T=1 Corporate] For guerrilla infiltrators only: always displays a penalty-free flee log on screen when you reach the defeat threshold."),
    "SHOES_CORP_05": ("Kang Tao Terrain-Adaptive Acid Boots", "[T=1 Corporate] Special shoes that forcibly pause the contamination buildup formula itself while crossing hazardous tiles like molten radioactive basins."),
    "SHOES_CORP_06": ("Biotechnica Organic Muscle-Fiber Walkers", "[T=1 Corporate] Shoes that, whenever the 7:3 stat distribution rule runs, boost 1 point of free AP into Vitality for free."),
    # --- 목걸이 (necklace) ---
    "NECK_CORP_01": ("Quantum-Weighted Stabilizer Choker", "[T=1 Corporate] A choker that binds the weight conversion coefficient of every hybrid unique skill to its maximum of 1.0, regardless of your actual stat imbalance."),
    "NECK_CORP_02": ("Arasaka License-Laundering Choker", "[T=1 Corporate] A smart necklace that logically launders away the debuff that raises firewall trace buildup by 200% on entering Neo Arc."),
    "NECK_CORP_03": ("Militech Tactical Core Sync Chain", "[T=1 Corporate] A necklace that reduces the tier-gap penalty by one more step when transferring enhancement from a weapon to armor."),
    "NECK_CORP_04": ("Orbital Air Zero-G Wiring Pendant", "[T=1 Corporate] A chain that ignores carry weight limits and mercilessly cuts the resource binding penalty of equipping tier-0 endgame relics by a percentage."),
    "NECK_CORP_05": ("Kang Tao Analysis Matrix Decoder Choker", "[T=1 Corporate] A compute gadget that links the weighting of 1% ghost data box detection and ancient relic analysis success when searching the field."),
    "NECK_CORP_06": ("Biotechnica Bio-Loop Ring Chain", "[T=1 Corporate] A necklace that always boosts the base natural decay constant recovered each turn by +5 as physical or compute contamination stacks build."),
    # --- 반지 (ring) ---
    "RING_CORP_01": ("Neo Arc High Official's Signet", "[T=1 Corporate] Engraved with a senior Bureau official's digital signature, this signet always shows a 100% success log when running virtual safehouse node laundering."),
    "RING_CORP_02": ("Arasaka Glitch-Loop Smart Ring", "[T=1 Corporate] A ring that snags the counter-element resistance of Titan Crushers and Grid Hunters with hacking tools, always cutting it by 30%."),
    "RING_CORP_03": ("Militech Master Refining Resonance Loop", "[T=1 Corporate] An enhancement-support ring that has a 50% chance to save high-value resources lost when resonance refining (enhancement) fails."),
    "RING_CORP_04": ("Orbital Air RAM Burst Ring", "[T=1 Corporate] A compute loop that, on a successful RAM-cost skill, has a 20% chance to instantly refund 100% of the RAM spent."),
    "RING_CORP_05": ("Kang Tao Stat Resonance Gadget Loop", "[T=1 Corporate] A smart ring that relaxes the hardcore turn requirement of [Signal-Locked Traits] to just 3 consecutive successes."),
    "RING_CORP_06": ("Biotechnica Absorption Overlay Ring", "[T=1 Corporate] A ring that always doubles the survival and HP absorbed when the hybrid unique skill [Bio Reap] triggers."),
    # --- 특화부품 (custom_part) ---
    "PART_CORP_01": ("Void Injector Module (v1.2)", "[T=1 Corporate] [Net - Protocol Breaker] Raises the [Protocol Glitch] success cap to 85% / [Penalty] Each successful forgery permanently locks 1 available RAM and instantly adds +20 to the city firewall trace index."),
    "PART_CORP_02": ("Arasaka Nano Clock Accelerator Chip", "[T=1 Corporate] [Combat - Infiltrating Striker] Initiative index (INIT) forcibly doubled while unique skill [Overclock] is active / [Penalty] Contamination resistance locked at 0% for those combat turns."),
    "PART_CORP_03": ("Militech Piercing Tactical Wiring Patch", "[T=1 Corporate] [Combat - Tactical Infantry] Supercharges the debuff weight of all your physical damage, permanently cutting enemy effective defense by 50% / [Penalty] Your base Vitality forcibly fixed at -500."),
    "PART_CORP_04": ("NeoNet Wide-Area Virus Master Pack", "[T=1 Corporate] [Net - Classic Netrunner] Indiscriminate virus packets paralyze the compute power of every mech-beast on the field and boost final damage multiplier by +15% / [Penalty] Inventory weight limit locked at -10kg."),
    "PART_CORP_05": ("Kang Tao Sentry Algorithm Overlay", "[T=1 Corporate] [Net - Autonomous Engineer] Locks [Sentry Infra] turret range, accuracy, and skill trigger formulas to values multiplied by your peak Intellect / [Penalty] 30% chance your virtual safehouse is instantly shut down when a turret is destroyed."),
    "PART_CORP_06": ("Biotechnica Severing-Log Extraction Tip", "[T=1 Corporate] [Combat - Bio Reaper] Boosts the [Bio Reap] trigger chance formula to its cap of 80% / [Penalty] Hunger/thirst always drain +3 faster at the end of every turn."),

    # ===== [0등급: 유물 (Legacy)] =====
    # --- 주무기 (main_weapon) ---
    "WEAPON_LEGACY_01": ("Excalibur Proto", "[T=0 Relic / Base: Arasaka Nano Laser Katana] The pinnacle of physical scale. Dominates the log with [hundred-million damage] on hit and forces the cybernetic severing flag 100% of the time."),
    "WEAPON_LEGACY_02": ("Rebuilt Hyperion Rail Master", "[T=0 Relic / Base: Militech Service Railgun v9] Absolute penetration that erases an enemy mech-beast's final effective defense from the formula and treats it as 0."),
    "WEAPON_LEGACY_03": ("Singularity Chrono Blaster", "[T=0 Relic / Base: Orbital Air Plasma Blaster] Its field warps the code of the time axis. On hit, it nullifies the enemy's initiative (INIT) calculation and deletes their next turn entirely."),
    "WEAPON_LEGACY_04": ("Medusa Nano-Virus Overload", "[T=0 Relic / Base: Biotechnica Neurotoxin Emitter] Sprays cell-collapse packets, piling +50 spreading contamination stacks onto every enemy's nervous system each turn."),
    "WEAPON_LEGACY_05": ("Azathoth Dimensional Guided Injector", "[T=0 Relic / Base: Kang Tao Micro Smart Pistol] Reduces enemy evasion and status resistance to 0%, and every hit in the combat log is computed as a guaranteed critical."),
    "WEAPON_LEGACY_06": ("Gaia Bio-Shredder Silencer", "[T=0 Relic / Base: Trauma Team HF Cutting Scalpel] In clashes with human raider raids, permanently steals the main weapon power of the whole mercenary squad and encodes it into your own."),
    # --- 사이버덱 (cyberdeck) ---
    "DECK_LEGACY_01": ("Neo Arc Overlord Core", "[T=0 Relic / Base: Neo Arc Security Agent Deck] Disguises the Master AI's surveillance net itself as a friendly node, completely sealing off security raids on virtual safehouses in Neo Arc."),
    "DECK_LEGACY_02": ("Void Architect v4.0", "[T=0 Relic / Base: NeoNet Quantum Mainframe Core] Distorts virtual law code. Hacks the very log of the hundreds of millions of damage enemies deal, laundering it into [ 0 damage ] or friendly fire."),
    "DECK_LEGACY_03": ("Aegis Matrix God Shield", "[T=0 Relic / Base: Militech Tactical Firewall Deck] Fully blocks the brain-damage recoil code of beasts' digital counter-hacks and converts the reflected damage back at massive scale in real time."),
    "DECK_LEGACY_04": ("Old-World Legacy: Protocol Destroyer", "[T=0 Relic / Base: Microtech High-Speed Packetware] Runs wide-area virus acceleration at a godlike level, paralyzing the group control cores of every mech-beast on the field within 1 turn."),
    "DECK_LEGACY_05": ("Yggdrasil Lifeline Backdoor", "[T=0 Relic / Base: Biotechnica Organic Circuit Deck] On a successful RAM-cost skill, converts 100% of the compute resources spent into displayed Vitality in real time."),
    "DECK_LEGACY_06": ("Anarchist Void Apocalypse", "[T=0 Relic / Base: Arasaka Darknet Protocol Deck] Erases the system cap formula on [Protocol Glitch] success itself, blocking enemy hits and movement with error logs."),
    # --- 의체부품 (cybernetic_parts) ---
    "CYBER_LEGACY_01": ("Prototype Hyperion Core", "[T=0 Relic / Base: Trauma Team Bioware Engine] Perfectly optimizes bodily fatigue. Preset-locks the reduction of survival drain on wasteland tiles at its peak of 60%."),
    "CYBER_LEGACY_02": ("Atlas Military Crusher Arm", "[T=0 Relic / Base: Militech Enhanced Strength Servo Arm] Combat Force only. Destroys the stepped efficiency falloff of the Vitality conversion curve f(A), locking it at 100% efficiency."),
    "CYBER_LEGACY_03": ("Chronos Phase Reflex Guard", "[T=0 Relic / Base: Arasaka Nano Reflex Network] Erases the Agility diminishing-returns threshold entirely, permanently securing the first turn in initiative (INIT) calculations."),
    "CYBER_LEGACY_04": ("Singularity Energy Geiger Heart", "[T=0 Relic / Base: Orbital Bio Radiation Filter Core] Completely erases the contamination stacks that build in the deepest irradiated zones, granting permanent immunity to physical/compute contamination penalties."),
    "CYBER_LEGACY_05": ("Void-Fused Neural Overlay", "[T=0 Relic / Base: Kang Tao Intelligent Compute Cortex] Neutralizes the Intellect diminishing-returns threshold and always locks ancient relic analysis and frequency detection success at a perfect 100%."),
    "CYBER_LEGACY_06": ("Old-World Masterpiece Bio-Engine", "[T=0 Relic / Base: Biotechnica Organic Artificial Heart] Under the 7:3 late-game growth rule, permanently hyper-scales the stat value of earned free ability points (AP) by 2x."),
    # --- 등 장비 (back_gear) ---
    "BACK_LEGACY_01": ("Phase-Shift Dimensional Leap Booster", "[T=0 Relic / Base: Technocracy Jet Booster] A spatial leap device. Freezes the field ambush rate variable at 0 and erases wasteland bad-weather movement penalty logs."),
    "BACK_LEGACY_02": ("Void Space Compression Infra", "[T=0 Relic / Base: Nano-Carbon Expanding Logistics Pack] Deletes the carry weight rule from the system entirely. Weight limits are permanently lifted."),
    "BACK_LEGACY_03": ("Master AI Trace Eternal Nullifier", "[T=0 Relic / Base: Corporate Infinite Cooling Tower] Completely bypasses the pattern exposure penalty function for spamming one unique skill, always guaranteeing 100% damage."),
    "BACK_LEGACY_04": ("Engineer Grid Automata Pack", "[T=0 Relic / Base: Tactical Guided Drone Rack] Lock-encodes your turrets' skill trigger rate and crit multiplier formulas at an absolute peak beyond their normal limits."),
    "BACK_LEGACY_05": ("Tesla Infinite Power Backpack", "[T=0 Relic / Base: Orbital Air Energy Accelerator Cell] When holding a base barrier or during base raids, generator durability and barrier resources auto-repair to max every turn."),
    "BACK_LEGACY_06": ("Ghost Node Eternal Squatting Wrapper", "[T=0 Relic / Base: Microtech Signal Deflector] Indefinitely defers the Master AI's full security-neutralization patch cycle for holding the same node too long."),
    # --- 안면 (face) ---
    "FACE_LEGACY_01": ("Void Watcher's Perfect Visage", "[T=0 Relic / Base: Bureau Hologram Visor] Limiter-locks the crit chance formula at its cap of 75% and further amplifies the crit multiplier on first-turn checks."),
    "FACE_LEGACY_02": ("Old-World Invincible Master Helmet", "[T=0 Relic / Base: Arasaka Heavy Armor Hyper Helmet] Always cuts by a percentage the physical hits of barrens raider raids and Bureau cleanup squad ambushes triggered by the reputation zero-sum rule."),
    "FACE_LEGACY_03": ("Apocalypse Geiger Fury Mask", "[T=0 Relic / Base: Militech Tactical Full-Face Gas Mask] On hazardous environment tiles, locks the status and elemental resistance check weight at the absolute highest safety line."),
    "FACE_LEGACY_04": ("Singularity Clock Eye", "[T=0 Relic / Base: Kang Tao Variable Multifocal Glasses] Permanently lifts the paralysis bracket of Intellect's effective value function, locking enemy wiring-scan debuff performance at its cap of 50%."),
    "FACE_LEGACY_05": ("Boundary Breaker Matrix HUD", "[T=0 Relic / Base: Orbital Air Pressurized HUD Visor] An absolute-precision gadget that permanently holds the base multiplier margin of the crit damage formula at its peak."),
    "FACE_LEGACY_06": ("Ripperdoc Nano Barcode Scanner", "[T=0 Relic / Base: Biotechnica Cell Analysis Goggles] Breaks the limit and preset-locks the base constant of the [Bio Reap] trigger chance formula at a permanent 80%."),
    # --- 상의외장 (top) ---
    "TOP_LEGACY_01": ("Boundary Guard Plate", "[T=0 Relic / Base: Bureau Security Nano-Fiber Suit] Dynamically guarantees displayed Vitality in the tens of thousands and above, and blows up the fixed constant of the physical defense formula."),
    "TOP_LEGACY_02": ("Anarchist's Distortion Outer Coat", "[T=0 Relic / Base: Executive Firewall Long Coat] Completely launders away both the 200% firewall trace buildup debuff on entering the city and the chance of forced virtual safehouse shutdown."),
    "TOP_LEGACY_03": ("Shogun Overclock Nano Harness Armor", "[T=0 Relic / Base: Arasaka Military Nano-Plate Cuirass] While the Overclock combat script runs, plants an immunity flag in your armor, forcing enemy effective penetration to 0."),
    "TOP_LEGACY_04": ("Wasteland Resistance Chief's Great Armor", "[T=0 Relic / Base: Militech Cleanup Squad Heavy Guardian] At the reputation threshold, forcibly cuts the damage weighting of hostile factions, and steals enemy weapon power on victory."),
    "TOP_LEGACY_05": ("Glitch Reality Crash Suit", "[T=0 Relic / Base: Orbital Air Shock-Absorbing Tactical Suit] Converts mutant beasts' signature gimmick strikes and wide-area shrapnel noise buildup into VR encoding error logs, nullifying them at the source."),
    "TOP_LEGACY_06": ("Golden Ratio Resonance Overcoat", "[T=0 Relic / Base: Kang Tao Hybrid Resonance Vest] Forcibly unlocks the [Hybrid Resonance] trait, locking the conversion rate of every unique skill at its peak regardless of your stat spread."),
    # --- 하의외장 (bottom) ---
    "BOTTOM_LEGACY_01": ("Anarchist's Distortion Pants", "[T=0 Relic / Base: Executive Tactical Pants] Deletes the resource cost weight of lower-body joint motors. Freezes the survival drain formula for wasteland tile movement at its default value."),
    "BOTTOM_LEGACY_02": ("Darknet Infiltrator Over-Cargo", "[T=0 Relic / Base: Arasaka Security Guard Nano Jeans] During virtual safehouse node hacking sessions, mathematically erases RAM-leak contamination stacks and the Wanted debuff threshold trigger."),
    "BOTTOM_LEGACY_03": ("Absolute Grounding Insulated Leggings", "[T=0 Relic / Base: Militech Special Agent Insulated Cargo] Permanently refuses the fatal system-paralysis penalty protocol where compute contamination reaches 100 and locks available RAM at 0."),
    "BOTTOM_LEGACY_04": ("Phase-Shift Accelerated Shadow Cargo", "[T=0 Relic / Base: Orbital Air Mobility Accelerator Pants] Lifts the limiter on the base evasion formula, an Agility-derived stat, and locks it at the system's absolute ceiling of 50%."),
    "BOTTOM_LEGACY_05": ("Last-Stand Survivor Medical Gear", "[T=0 Relic / Base: Biotechnica Cell-Refining Overalls] Permanently slows survival drain, and injects a damage formula multiplier bonus while offline survival values are both at 90% or higher."),
    "BOTTOM_LEGACY_06": ("Servo-Link Hyper Balancer Jeans", "[T=0 Relic / Base: Kang Tao Tactical Hydraulic Pants] Blows open the mathematical margin of 30% free AP efficiency, securing Combat Force ambush first turns and enemy turn-freeze logs 100% of the time."),
    # --- 신발외장 (footwear) ---
    "SHOES_LEGACY_01": ("Dimensional Leap Phase Boots", "[T=0 Relic / Base: Maglev Mobility Shoes] Erases the ground friction constant. Plants an unrivaled multiplier in the initiative (INIT) formula, locking in the first turn before enemies even notice you."),
    "SHOES_LEGACY_02": ("Ghost in the Shell Shadow Walker", "[T=0 Relic / Base: Arasaka Nano Silent Tactical Walkers] Holds noise/power signal buildup at a zero pointer, perfectly bypassing the anti-farming mutant beast raid clause for repeated efficient patterns."),
    "SHOES_LEGACY_03": ("Guardian Infra Titan Safety Boots", "[T=0 Relic / Base: Militech Heavy Assault Safety Boots] On a successful opening ambush, always injects knockback immunity and base barrier regeneration protocols directly into your whole party."),
    "SHOES_LEGACY_04": ("Signal Dasher Infinity Shoes", "[T=0 Relic / Base: Orbital Air Phase-Sync Boots] Guerrilla infiltrator specialty. To seal off the risk of defeat, always forces a penalty-free flee log onto the screen."),
    "SHOES_LEGACY_05": ("Radioactive Basin Master Boots", "[T=0 Relic / Base: Kang Tao Terrain-Adaptive Acid Boots] While moving across hazardous tiles like irradiated zones, forcibly pauses the very clause that accrues physical contamination per turn."),
    "SHOES_LEGACY_06": ("AP Resonance Overclock Shoes", "[T=0 Relic / Base: Biotechnica Organic Muscle-Fiber Walkers] Each time the 7:3 growth split runs, parses free AP value as a multiplier instead of an addition, expanding the limits of your build."),
    # --- 목걸이 (necklace) ---
    "NECK_LEGACY_01": ("Old-World Legacy: Chronos Pendant", "[T=0 Relic / Base: Quantum-Weighted Stabilizer Choker] Locks the conversion coefficient matrix of every unique skill interaction at an absolute 1.0, regardless of your actual stat spread."),
    "NECK_LEGACY_02": ("City Surveillance Master Bypasser", "[T=0 Relic / Base: Arasaka License-Laundering Choker] Freezes firewall trace buildup at 0 while you stay in the city, keeping you logged as a legal white-hat agent at all times."),
    "NECK_LEGACY_03": ("One-Way Value-Preserving Encoder Choker", "[T=0 Relic / Base: Militech Tactical Core Sync Chain] When transferring main weapon/cyberdeck refinement to armor, always waives 100% of the tier-gap reduction."),
    "NECK_LEGACY_04": ("Relic Resource-Binding Hyper Deflector", "[T=0 Relic / Base: Orbital Air Zero-G Wiring Pendant] Forcibly cuts to decimals the constant of the rapid per-turn survival depletion penalty from stacking endgame relic gear."),
    "NECK_LEGACY_05": ("Ghost Data Box Absolute Extractor", "[T=0 Relic / Base: Kang Tao Analysis Matrix Decoder Choker] Boosts the detection script for the hidden 1% ghost data box in the barrens and the final resource drop log by a fixed amount."),
    "NECK_LEGACY_06": ("Absolute Contamination Overflow Surge", "[T=0 Relic / Base: Biotechnica Bio-Loop Ring Chain] As physical/compute contamination ticks build, always boosts the natural decay constant recovered each turn by +10, preventing contamination paralysis."),
    # --- 반지 (ring) ---
    "RING_LEGACY_01": ("Singularity Loop", "[T=0 Relic / Base: Neo Arc High Official's Signet] Disrupts at the source the Master AI security patches applied while squatting on a virtual safehouse node, securing a guaranteed 100% success log."),
    "RING_LEGACY_02": ("Counter-Mutant AI Matrix Break", "[T=0 Relic / Base: Arasaka Glitch-Loop Smart Ring] Completely shreds the native resistance matrix of mutant beasts like Titan Crushers and Grid Hunters with hacking tools."),
    "RING_LEGACY_03": ("Safety-Ceiling Resonance Absolute Ring", "[T=0 Relic / Base: Militech Master Refining Resonance Loop] Forcibly bypasses resource loss when resonance refining (enhancement) fails and doubles the accumulated bonus chance for the next attempt."),
    "RING_LEGACY_04": ("Infinity RAM Script Surge Ring", "[T=0 Relic / Base: Orbital Air RAM Burst Ring] When running RAM-cost unique skills, breaks through an overwhelming 50% chance barrier to refund 100% of the compute resources spent."),
    "RING_LEGACY_05": ("Signal-Locked Resonance Master Ring", "[T=0 Relic / Base: Kang Tao Stat Resonance Gadget Loop] Instantly unlocks hidden-condition trait flags such as [Last-Stand Survivor] and [Silence of the Master AI's Eye], regardless of your current session state."),
    "RING_LEGACY_06": ("Survival-Backflow Hyper Cycle Ring", "[T=0 Relic / Base: Biotechnica Absorption Overlay Ring] While the hybrid unique skill [Bio Reap] is active, permanently triples the survival absorption formula with no cap."),
    # --- 특화부품 (custom_part) ---
    "PART_LEGACY_01": ("Rebuilt Masterpiece Void Injector", "[T=0 Relic / Base: Void Injector Module (v1.2)] [Net - Protocol Breaker] Deletes the [Protocol Glitch] success cap formula and locks it at up to 85% / [Penalty] Each successful forgery session permanently locks 1 available RAM and instantly adds +20 to the city firewall trace index."),
    "PART_LEGACY_02": ("Arasaka Chronos Clock Chip vMax", "[T=0 Relic / Base: Arasaka Nano Clock Accelerator Chip] [Combat - Infiltrating Striker] Initiative (INIT) forcibly doubled while unique skill [Overclock] is active / [Penalty] Your contamination resistance forcibly locked at 0% for those combat turns."),
    "PART_LEGACY_03": ("Militech Frame-Shredder Master Patch", "[T=0 Relic / Base: Militech Piercing Tactical Wiring Patch] [Combat - Tactical Infantry] Supercharges the debuff weight of physical damage, permanently cutting enemy effective defense by 50% / [Penalty] Your base Vitality forcibly fixed at -500."),
    "PART_LEGACY_04": ("NeoNet Grid Annihilation Virus Package", "[T=0 Relic / Base: NeoNet Wide-Area Virus Master Pack] [Net - Classic Netrunner] Indiscriminate virus spread stacks compute paralysis on every mech-beast on the field and boosts final damage multiplier by +15% / [Penalty] Inventory weight limit locked at -10kg."),
    "PART_LEGACY_05": ("Kang Tao Sentry Autonomous Factory Overlay", "[T=0 Relic / Base: Kang Tao Sentry Algorithm Overlay] [Net - Autonomous Engineer] Force-locks [Sentry Infra] turret trigger rate and range to your peak Intellect function score / [Penalty] 30% chance your virtual safehouse is instantly shut down when a turret is destroyed."),
    "PART_LEGACY_06": ("Biotechnica Hyper Ripper Extraction Chip", "[T=0 Relic / Base: Biotechnica Severing-Log Extraction Tip] [Combat - Bio Reaper] Boosts the [Bio Reap] trigger chance formula to its cap of 80% / [Penalty] Hunger/thirst drain always +3 faster at the end of every turn."),
}
